<script setup lang="ts">
import { computed, ref } from 'vue'
import { login, register } from '../auth/authApi'
type Mode='login'|'register'
const mode=ref<Mode>('login'), identifier=ref(''), password=ref(''), nickname=ref(''), message=ref(''), submitting=ref(false)
const emit=defineEmits<{done:[]}>(), isRegister=computed(()=>mode.value==='register')
function validate(){const account=identifier.value.trim();if(!account)return '请输入手机号或邮箱。';if(account.includes('@')?!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(account):!/^[+]?[-\s0-9]{6,20}$/.test(account))return '请输入有效的手机号或邮箱。';if(!password.value)return '请输入密码。';if(isRegister.value&&!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,128}$/.test(password.value))return '密码需为 8-128 位，并包含大小写字母和数字。';return ''}
async function submit(){message.value=validate();if(message.value||submitting.value)return;submitting.value=true;try{if(isRegister.value)await register(identifier.value,password.value,nickname.value);else await login(identifier.value.trim(),password.value);emit('done')}catch(error){message.value=error instanceof Error&&error.message==='REQUEST_409'?'该手机号或邮箱已注册，请直接登录。':isRegister.value?'注册失败，请检查信息后重试。':'账号或密码错误。'}finally{submitting.value=false}}
</script>
<template><section class="auth-page"><div class="auth-intro"><div class="auth-brand"><span class="brand-mark">✦</span><span>Cloud Ticketing</span></div><div class="auth-intro-copy"><p class="eyebrow">LIVE EXPERIENCES</p><h1>把下一场现场，<br><em>留给你。</em></h1><p>探索城市里的音乐、戏剧与现场活动，提前选好属于你的最佳位置。</p></div><div class="auth-perks"><span>✓ 安全账户体系</span><span>✓ 即时确认座位</span></div></div><div class="auth-card"><div class="auth-card-heading"><div><p class="eyebrow">YOUR TICKET DESK</p><h2>{{isRegister?'创建你的账号':'欢迎回来'}}</h2><p class="auth-subtitle">{{isRegister?'注册后即可浏览活动并完成选座。':'登录后继续你的选座旅程。'}}</p></div><span class="auth-card-icon">✦</span></div><div class="auth-tabs" role="tablist"><button type="button" role="tab" :aria-selected="!isRegister" :class="{active:!isRegister}" @click="mode='login'">登录</button><button type="button" role="tab" data-testid="register-toggle" :aria-selected="isRegister" :class="{active:isRegister}" @click="mode='register'">注册</button></div><form class="auth-form" @submit.prevent="submit"><label class="auth-field"><span>手机号或邮箱</span><span class="auth-input-wrap"><input v-model="identifier" placeholder="name@example.com / 13800138000" autocomplete="username"></span></label><label v-if="isRegister" class="auth-field"><span>昵称 <small>可选</small></span><span class="auth-input-wrap"><input v-model="nickname" data-testid="nickname-input" placeholder="现场见面时怎么称呼你？" autocomplete="nickname"></span></label><label class="auth-field"><span>密码</span><span class="auth-input-wrap"><input v-model="password" type="password" placeholder="请输入密码" autocomplete="current-password"></span></label><p v-if="isRegister" class="auth-hint">至少 8 位，需包含大写、小写字母和数字</p><div v-if="message" class="auth-message" role="alert">{{message}}</div><button class="primary-btn auth-submit" data-testid="submit-auth" :disabled="submitting">{{submitting?'请稍候...':isRegister?'注册并进入':'登录'}} →</button></form><p class="auth-footnote">继续即表示你同意 Cloud Ticketing 的服务条款与隐私政策。</p></div></section></template>
