FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY . .
RUN mvn -s /workspace/maven-settings.xml -q -pl services/promotion-service -am package -DskipTests
FROM eclipse-temurin:21-jre
COPY --from=build /workspace/services/promotion-service/target/promotion-service-0.1.0-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
