package com.cloudticket.activity.service;
import java.util.*; import java.util.concurrent.ConcurrentHashMap; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import com.cloudticket.activity.security.ScopeAccess;
@Service public class ActivityCatalog {
 private final Map<String,Activity> activities=new ConcurrentHashMap<>();
 private final JdbcTemplate jdbc;
 public ActivityCatalog(){this.jdbc=null; seed("星河现场 · 城市之声","星河文化","PUBLISHED"); seed("海岸线音乐节","海岸现场","PUBLISHED");}
 @org.springframework.beans.factory.annotation.Autowired public ActivityCatalog(JdbcTemplate jdbc){this.jdbc=jdbc;}
 private void seed(String title,String organizer,String status){Activity a=create(title,organizer); activities.put(a.id(),new Activity(a.id(),a.title(),a.organizer(),status,false));}
 public Activity create(String title,String organizer){if(title==null||title.isBlank())throw new IllegalArgumentException("title required"); String id=UUID.randomUUID().toString(), cleanOrganizer=organizer==null?"":organizer.trim(); if(jdbc!=null)jdbc.update("INSERT INTO activity (id,title,organizer,status) VALUES (?,?,?, 'OFFLINE')",id,title.trim(),cleanOrganizer); Activity a=new Activity(id,title.trim(),cleanOrganizer,"OFFLINE",false);activities.put(a.id(),a);return a;}
 public Activity update(String id,String title,String organizer){Activity current=get(id);if(current.layoutFrozen())throw new IllegalStateException("layout is frozen");if(title==null||title.isBlank())throw new IllegalArgumentException("title required");String cleanTitle=title.trim(),cleanOrganizer=organizer==null?"":organizer.trim();if(jdbc!=null)jdbc.update("UPDATE activity SET title=?,organizer=? WHERE id=?",cleanTitle,cleanOrganizer,id);Activity updated=new Activity(id,cleanTitle,cleanOrganizer,current.status(),current.layoutFrozen());activities.put(id,updated);return updated;}
 public List<Activity> publicActivities(){if(jdbc!=null)return jdbc.query("SELECT DISTINCT a.id,a.title,a.organizer,a.status,a.layout_frozen FROM activity a JOIN activity_session s ON s.activity_id=a.id WHERE s.status='ONSALE' ORDER BY a.title",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")));return activities.values().stream().filter(a->"PUBLISHED".equals(a.status())).sorted(Comparator.comparing(Activity::title)).toList();}
 public Page<Activity> publicActivities(String keyword,String organizer,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));String kw=keyword==null?"":keyword.trim(),org=organizer==null?"":organizer.trim();if(jdbc==null){var all=activities.values().stream().filter(a->"PUBLISHED".equals(a.status())).filter(a->(kw.isBlank()||a.title().toLowerCase().contains(kw.toLowerCase()))&&(org.isBlank()||a.organizer().toLowerCase().contains(org.toLowerCase()))).sorted(Comparator.comparing(Activity::title)).toList();int from=Math.min(p*s,all.size());return new Page<>(all.subList(from,Math.min(from+s,all.size())),p,s,all.size());}Integer total=jdbc.queryForObject("SELECT COUNT(DISTINCT a.id) FROM activity a JOIN activity_session s ON s.activity_id=a.id WHERE s.status='ONSALE' AND (?='' OR a.title LIKE CONCAT('%',?,'%')) AND (?='' OR a.organizer LIKE CONCAT('%',?,'%'))",Integer.class,kw,kw,org,org);var items=jdbc.query("SELECT a.id,a.title,a.organizer,a.status,a.layout_frozen FROM activity a JOIN activity_session s ON s.activity_id=a.id WHERE s.status='ONSALE' AND (?='' OR a.title LIKE CONCAT('%',?,'%')) AND (?='' OR a.organizer LIKE CONCAT('%',?,'%')) GROUP BY a.id,a.title,a.organizer,a.status,a.layout_frozen ORDER BY a.title LIMIT ? OFFSET ?",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")),kw,kw,org,org,s,p*s);return new Page<>(items,p,s,total==null?0:total);}
 public Page<Activity> adminActivities(String keyword,String status,int page,int size){int safePage=Math.max(0,page), safeSize=Math.min(100,Math.max(1,size)); if(jdbc==null){var all=activities.values().stream().filter(a->(keyword==null||keyword.isBlank()||a.title().toLowerCase().contains(keyword.toLowerCase()))&&(status==null||status.isBlank()||status.equals(a.status()))).sorted(Comparator.comparing(Activity::title)).toList();int from=Math.min(safePage*safeSize,all.size());return new Page<>(all.subList(from,Math.min(from+safeSize,all.size())),safePage,safeSize,all.size());}String kw=keyword==null?"":keyword.trim();String st=status==null?"":status.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM activity WHERE (?='' OR title LIKE CONCAT('%',?,'%')) AND (?='' OR status=?)",Integer.class,kw,kw,st,st);var items=jdbc.query("SELECT id,title,organizer,status,layout_frozen FROM activity WHERE (?='' OR title LIKE CONCAT('%',?,'%')) AND (?='' OR status=?) ORDER BY title LIMIT ? OFFSET ?",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")),kw,kw,st,st,safeSize,safePage*safeSize);return new Page<>(items,safePage,safeSize,total==null?0:total);}
 public Page<Activity> adminActivities(String keyword,String status,int page,int size,String permissions,String scopes){
   if (ScopeAccess.allows(permissions, scopes, "ACTIVITY", "*")) return adminActivities(keyword,status,page,size);
   int p=Math.max(0,page), s=Math.min(100,Math.max(1,size)); String kw=keyword==null?"":keyword.trim().toLowerCase(), st=status==null?"":status.trim();
   List<Activity> all=jdbc==null?activities.values().stream().filter(a->(kw.isBlank()||a.title().toLowerCase().contains(kw))&&(st.isBlank()||st.equals(a.status()))).toList():jdbc.query("SELECT id,title,organizer,status,layout_frozen FROM activity WHERE (?='' OR title LIKE CONCAT('%',?,'%')) AND (?='' OR status=?) ORDER BY title",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")),kw,kw,st,st);
   List<Activity> visible=all.stream().filter(a->visibleActivity(a.id(),permissions,scopes)).toList(); int from=Math.min(p*s,visible.size()); return new Page<>(visible.subList(from,Math.min(from+s,visible.size())),p,s,visible.size());
 }
 private boolean visibleActivity(String id,String permissions,String scopes){
   if(ScopeAccess.allows(permissions,scopes,"ACTIVITY",id)) return true;
   if(jdbc==null||scopes==null||scopes.isBlank()) return false;
   String normalized=scopes.replace(" ","");
   if(normalized.toUpperCase().contains("SESSION:*")||normalized.toUpperCase().contains("VENUE:*")) return true;
   Integer session=jdbc.queryForObject("SELECT COUNT(*) FROM activity_session WHERE activity_id=? AND FIND_IN_SET(CONCAT('SESSION:',id), ?) > 0",Integer.class,id,normalized);
   if(session!=null&&session>0) return true;
   Integer venue=jdbc.queryForObject("SELECT COUNT(*) FROM venue WHERE activity_id=? AND FIND_IN_SET(CONCAT('VENUE:',id), ?) > 0",Integer.class,id,normalized);
   return venue!=null&&venue>0;
 }
 public Activity get(String id){if(jdbc!=null){var rows=jdbc.query("SELECT id,title,organizer,status,layout_frozen FROM activity WHERE id=?",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")),id);if(!rows.isEmpty())return rows.get(0);}Activity a=activities.get(id);if(a==null)throw new NoSuchElementException("activity not found");return a;}
 public List<Session> sessions(String activityId){if(jdbc==null)return List.of(new Session("20000000-0000-0000-0000-000000000001",activityId,"2026-10-01T19:30:00","2026-10-01T22:00:00","星河剧场","ONSALE"));return jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status,s.price_minor FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.activity_id=? AND s.status='ONSALE' ORDER BY s.starts_at",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status"),r.getInt("price_minor")),activityId);}
 public List<Seat> seats(String sessionId){if(jdbc==null)return List.of();return jdbc.query("SELECT id,row_label,seat_number,status FROM seat WHERE session_id=? ORDER BY row_label,seat_number",(r,n)->new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),sessionId);}
 public List<SeatLayout> seatLayouts(String sessionId){if(jdbc==null)return List.of();return jdbc.query("SELECT id,area_label,row_label,seat_number,display_name,position_x,position_y,seat_type,status FROM seat WHERE session_id=? ORDER BY area_label,position_y,position_x,row_label,seat_number",(r,n)->new SeatLayout(r.getString("id"),r.getString("area_label"),r.getString("row_label"),r.getInt("seat_number"),r.getString("display_name"),r.getBigDecimal("position_x")==null?0:r.getBigDecimal("position_x").intValue(),r.getBigDecimal("position_y")==null?0:r.getBigDecimal("position_y").intValue(),r.getString("seat_type"),r.getString("status")),sessionId);}
 public List<SeatSnapshot> sessionSeatSnapshots(String sessionId){if(jdbc==null)return List.of();return jdbc.query("SELECT id,area_label,row_label,seat_number,display_name,position_x,position_y,seat_type,status FROM seat WHERE session_id=? ORDER BY row_label,seat_number",(r,n)->new SeatSnapshot(r.getString("id"),r.getString("area_label"),r.getString("row_label"),r.getInt("seat_number"),r.getString("display_name"),r.getBigDecimal("position_x")==null?0:r.getBigDecimal("position_x").intValue(),r.getBigDecimal("position_y")==null?0:r.getBigDecimal("position_y").intValue(),r.getString("seat_type"),r.getString("status")),sessionId);}
 public Page<Seat> seatsForActivity(String activityId,String permissions,String scopes,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));if(jdbc==null)return new Page<>(List.of(),p,s,0);var all=jdbc.query("SELECT s.id,s.row_label,s.seat_number,s.status,s.session_id FROM seat s JOIN activity_session x ON x.id=s.session_id WHERE x.activity_id=? ORDER BY x.starts_at,s.row_label,s.seat_number",(r,n)->new Object[]{new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),r.getString("session_id")},activityId);var visible=all.stream().filter(row->ScopeAccess.allows(permissions,scopes,"SESSION",(String)row[1],activityId)).map(row->(Seat)row[0]).toList();int from=Math.min(p*s,visible.size());return new Page<>(visible.subList(from,Math.min(from+s,visible.size())),p,s,visible.size());}
 public List<Venue> venues(String activityId){if(jdbc==null)return List.of();return jdbc.query("SELECT id,activity_id,name,address,capacity FROM venue WHERE (?='' OR activity_id=?) ORDER BY name",(r,n)->new Venue(r.getString("id"),r.getString("activity_id"),r.getString("name"),r.getString("address"),r.getInt("capacity")),activityId==null?"":activityId,activityId==null?"":activityId);}
 public List<Venue> venues(String activityId,String permissions,String scopes){
   return venues(activityId).stream().filter(v->ScopeAccess.allows(permissions,scopes,"VENUE",v.id(),v.activityId())).toList();
 }
 public Page<Venue> venuesPage(String keyword,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));if(jdbc==null)return new Page<>(List.of(),p,s,0);String kw=keyword==null?"":keyword.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM venue WHERE (?='' OR name LIKE CONCAT('%',?,'%'))",Integer.class,kw,kw);var items=jdbc.query("SELECT id,activity_id,name,address,capacity FROM venue WHERE (?='' OR name LIKE CONCAT('%',?,'%')) ORDER BY name LIMIT ? OFFSET ?",(r,n)->new Venue(r.getString("id"),r.getString("activity_id"),r.getString("name"),r.getString("address"),r.getInt("capacity")),kw,kw,s,p*s);return new Page<>(items,p,s,total==null?0:total);}
 public Venue updateVenue(String id,String name,String address){if(name==null||name.isBlank())throw new IllegalArgumentException("name required");String cleanName=name.trim(),cleanAddress=address==null?"":address.trim();if(jdbc!=null)jdbc.update("UPDATE venue SET name=?,address=? WHERE id=?",cleanName,cleanAddress,id);var rows=jdbc.query("SELECT id,activity_id,name,address,capacity FROM venue WHERE id=?",(r,n)->new Venue(r.getString("id"),r.getString("activity_id"),r.getString("name"),r.getString("address"),r.getInt("capacity")),id);if(rows.isEmpty())throw new NoSuchElementException("venue not found");return rows.get(0);}
 public Venue createVenue(String activityId,String name,String address){return createVenue(activityId,name,address,0);}
 public Venue createVenue(String activityId,String name,String address,int capacity){if(name==null||name.isBlank())throw new IllegalArgumentException("name required");if(capacity<0)throw new IllegalArgumentException("capacity must be non-negative");String id=UUID.randomUUID().toString(),cleanActivity=(activityId==null||activityId.isBlank())?null:activityId.trim(),cleanName=name.trim(),cleanAddress=address==null?"":address.trim();if(jdbc!=null)jdbc.update("INSERT INTO venue (id,activity_id,name,address,capacity) VALUES (?,?,?,?,?)",id,cleanActivity,cleanName,cleanAddress,capacity);return new Venue(id,cleanActivity,cleanName,cleanAddress,capacity);}
 public Venue getVenue(String id){if(jdbc!=null){var rows=jdbc.query("SELECT id,activity_id,name,address,capacity FROM venue WHERE id=?",(r,n)->new Venue(r.getString("id"),r.getString("activity_id"),r.getString("name"),r.getString("address"),r.getInt("capacity")),id);if(!rows.isEmpty())return rows.get(0);}throw new NoSuchElementException("venue not found");}
 public List<VenueSeat> venueSeats(String venueId){if(jdbc==null)return List.of();return jdbc.query("SELECT id,venue_id,area_label,row_label,seat_number,display_name,position_x,position_y,seat_type,enabled,status FROM venue_seat WHERE venue_id=? ORDER BY area_label,row_label,seat_number",(r,n)->new VenueSeat(r.getString("id"),r.getString("venue_id"),r.getString("area_label"),r.getString("row_label"),r.getInt("seat_number"),r.getString("display_name"),r.getBigDecimal("position_x")==null?0:r.getBigDecimal("position_x").intValue(),r.getBigDecimal("position_y")==null?0:r.getBigDecimal("position_y").intValue(),r.getString("seat_type"),r.getBoolean("enabled"),r.getString("status")),venueId);}
 public VenueSeat createVenueSeat(String venueId,String areaLabel,String rowLabel,int seatNumber,String displayName,int x,int y,String seatType,boolean enabled){if(venueId==null||venueId.isBlank()||rowLabel==null||rowLabel.isBlank()||seatNumber<=0)throw new IllegalArgumentException("venueId, rowLabel and positive seatNumber required");String id=UUID.randomUUID().toString(),area=areaLabel==null?"":areaLabel.trim(),row=rowLabel.trim(),display=displayName==null||displayName.isBlank()?row+"-"+seatNumber:displayName.trim(),type=seatType==null||seatType.isBlank()?"REGULAR":seatType.trim();VenueSeat s=new VenueSeat(id,venueId.trim(),area,row,seatNumber,display,x,y,type,enabled,"AVAILABLE");if(jdbc!=null){jdbc.update("INSERT INTO venue_seat (id,venue_id,area_label,row_label,seat_number,display_name,position_x,position_y,seat_type,enabled,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)",s.id(),s.venueId(),s.areaLabel(),s.rowLabel(),s.seatNumber(),s.displayName(),s.x(),s.y(),s.seatType(),s.enabled(),s.status());refreshVenueCapacity(venueId);}return s;}
 public VenueSeat updateVenueSeat(String id,String areaLabel,String rowLabel,int seatNumber,String displayName,int x,int y,String seatType,boolean enabled,String status){if(jdbc==null)return new VenueSeat(id,"",areaLabel==null?"":areaLabel,rowLabel,seatNumber,displayName,x,y,seatType==null?"REGULAR":seatType,enabled,status==null?"AVAILABLE":status);if(rowLabel==null||rowLabel.isBlank()||seatNumber<=0)throw new IllegalArgumentException("invalid seat");jdbc.update("UPDATE venue_seat SET area_label=?,row_label=?,seat_number=?,display_name=?,position_x=?,position_y=?,seat_type=?,enabled=?,status=? WHERE id=?",areaLabel==null?"":areaLabel.trim(),rowLabel.trim(),seatNumber,displayName==null?"":displayName.trim(),x,y,seatType==null?"REGULAR":seatType.trim(),enabled,status==null?"AVAILABLE":status.trim(),id);var rows=jdbc.query("SELECT id,venue_id,area_label,row_label,seat_number,display_name,position_x,position_y,seat_type,enabled,status FROM venue_seat WHERE id=?",(r,n)->new VenueSeat(r.getString("id"),r.getString("venue_id"),r.getString("area_label"),r.getString("row_label"),r.getInt("seat_number"),r.getString("display_name"),r.getBigDecimal("position_x")==null?0:r.getBigDecimal("position_x").intValue(),r.getBigDecimal("position_y")==null?0:r.getBigDecimal("position_y").intValue(),r.getString("seat_type"),r.getBoolean("enabled"),r.getString("status")),id);if(rows.isEmpty())throw new NoSuchElementException("venue seat not found");return rows.get(0);}
 public List<VenueSeat> generateVenueLayout(String venueId,String mode,Map<String,Object> rules){List<VenueSeat> generated=computeVenueLayout(venueId,mode,rules);if(jdbc!=null){jdbc.update("DELETE FROM venue_seat WHERE venue_id=?",venueId);for(VenueSeat s:generated)jdbc.update("INSERT INTO venue_seat (id,venue_id,area_label,row_label,seat_number,display_name,position_x,position_y,seat_type,enabled,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)",s.id(),s.venueId(),s.areaLabel(),s.rowLabel(),s.seatNumber(),s.displayName(),s.x(),s.y(),s.seatType(),s.enabled(),s.status());refreshVenueCapacity(venueId);}return generated;}
 private List<VenueSeat> computeVenueLayout(String venueId,String mode,Map<String,Object> rules){if(venueId==null||venueId.isBlank())throw new IllegalArgumentException("venueId required");String area=value(rules,"areaLabel");List<VenueSeat> out=new ArrayList<>();if("GRID".equalsIgnoreCase(mode)){int rows=parseInt(value(rules,"rowCount")),cols=parseInt(value(rules,"seatsPerRow"));if(rows<=0||cols<=0)throw new IllegalArgumentException("rowCount and seatsPerRow must be positive");boolean letters=!"NUMBER".equalsIgnoreCase(value(rules,"rowLabelType"));int start=Math.max(1,parseInt(value(rules,"startSeatNumber")));for(int i=0;i<rows;i++){String rowLabel=letters?rowLabel(i):String.valueOf(i+1);for(int j=0;j<cols;j++){int num=start+j;out.add(new VenueSeat(UUID.randomUUID().toString(),venueId.trim(),area,rowLabel,num,rowLabel+"-"+num,j,i,"REGULAR",true,"AVAILABLE"));}}}else if("ROWS".equalsIgnoreCase(mode)){Object raw=rules.get("rows");if(raw instanceof List<?> list){int y=0;for(Object item:list){if(!(item instanceof Map<?,?> m))continue;String rowLabel=value(m,"rowLabel");int count=parseInt(value(m,"seatCount"));int start=Math.max(1,parseInt(value(m,"startSeatNumber")));for(int j=0;j<count;j++){int num=start+j;out.add(new VenueSeat(UUID.randomUUID().toString(),venueId.trim(),area,rowLabel,num,rowLabel+"-"+num,j,y,"REGULAR",true,"AVAILABLE"));}y++;}}}else throw new IllegalArgumentException("mode must be GRID or ROWS");return out;}
 private String value(Map<?,?> m,String k){Object v=m.get(k);return v==null?"":String.valueOf(v);}
 private String rowLabel(int i){int n=i;StringBuilder sb=new StringBuilder();while(n>=0){sb.append((char)('A'+n%26));n=n/26-1;}return sb.reverse().toString();}
 private int parseInt(String value){try{return value==null||value.isBlank()?0:Integer.parseInt(value.trim());}catch(NumberFormatException e){throw new IllegalArgumentException("invalid number");}}
 public void deleteVenueSeat(String id){if(jdbc!=null){String venueId=jdbc.query("SELECT venue_id FROM venue_seat WHERE id=?",(r,n)->r.getString(1),id).stream().findFirst().orElse(null);jdbc.update("DELETE FROM venue_seat WHERE id=?",id);if(venueId!=null)refreshVenueCapacity(venueId);}}
 public void refreshVenueCapacity(String venueId){if(jdbc!=null)jdbc.update("UPDATE venue SET capacity=(SELECT COUNT(*) FROM venue_seat WHERE venue_id=?) WHERE id=?",venueId,venueId);}
 public Page<Session> adminSessions(String activityId,String status,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));if(jdbc==null)return new Page<>(sessions(activityId),p,s,sessions(activityId).size());String st=status==null?"":status.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM activity_session WHERE activity_id=? AND (?='' OR status=?)",Integer.class,activityId,st,st);var items=jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status,s.price_minor FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.activity_id=? AND (?='' OR s.status=?) ORDER BY s.starts_at LIMIT ? OFFSET ?",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status"),r.getInt("price_minor")),activityId,st,st,s,p*s);return new Page<>(items,p,s,total==null?0:total);}
 public Page<Session> adminSessions(String activityId,String status,int page,int size,String permissions,String scopes){
   if (ScopeAccess.allows(permissions,scopes,"ACTIVITY",activityId)) return adminSessions(activityId,status,page,size);
   int p=Math.max(0,page),s=Math.min(100,Math.max(1,size)); String st=status==null?"":status.trim();
   List<Session> all=jdbc==null?sessions(activityId):jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status,s.price_minor FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.activity_id=? AND (?='' OR s.status=?) ORDER BY s.starts_at",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status"),r.getInt("price_minor")),activityId,st,st);
   List<Session> visible=all.stream().filter(sx->{ if(ScopeAccess.allows(permissions,scopes,"SESSION",sx.id(),sx.activityId())) return true; if(jdbc==null) return false; String venueId=jdbc.query("SELECT venue_id FROM activity_session WHERE id=?",(r,n)->r.getString(1),sx.id()).stream().findFirst().orElse(""); return ScopeAccess.allows(permissions,scopes,"VENUE",venueId,sx.activityId()); }).toList();
   int from=Math.min(p*s,visible.size()); return new Page<>(visible.subList(from,Math.min(from+s,visible.size())),p,s,visible.size());
 }
 public Session createSession(String activityId,String venueId,String startsAt,String endsAt,String status){return createSession(activityId,venueId,startsAt,endsAt,status,0);}
 public Session createSession(String activityId,String venueId,String startsAt,String endsAt,String status,int priceMinor){if(startsAt==null||endsAt==null)throw new IllegalArgumentException("start and end required");var start=java.time.Instant.parse(startsAt);var end=java.time.Instant.parse(endsAt);if(!start.isBefore(end))throw new IllegalArgumentException("startsAt must be before endsAt");if(priceMinor<0)throw new IllegalArgumentException("price must be non-negative");if(jdbc==null)return new Session(UUID.randomUUID().toString(),activityId,startsAt,endsAt,"",status,priceMinor);String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO activity_session (id,activity_id,venue_id,starts_at,ends_at,status,price_minor) VALUES (?,?,?,?,?,?,?)",id,activityId,venueId,java.sql.Timestamp.from(start),java.sql.Timestamp.from(end),status,priceMinor);jdbc.update("INSERT INTO seat (id,session_id,area_label,row_label,seat_number,display_name,seat_type,position_x,position_y,status) SELECT UUID(),?,area_label,row_label,seat_number,display_name,seat_type,position_x,position_y,status FROM venue_seat WHERE venue_id=?",id,venueId);refreshActivityStatus(activityId);return sessionById(id);}
 public Session updateSession(String sessionId,String startsAt,String endsAt,String status){return updateSession(sessionId,startsAt,endsAt,status,0);}
 public Session updateSession(String sessionId,String startsAt,String endsAt,String status,int priceMinor){if(startsAt==null||endsAt==null)throw new IllegalArgumentException("start and end required");var start=java.time.Instant.parse(startsAt);var end=java.time.Instant.parse(endsAt);if(!start.isBefore(end))throw new IllegalArgumentException("startsAt must be before endsAt");if(priceMinor<0)throw new IllegalArgumentException("price must be non-negative");if(jdbc==null)return new Session(sessionId,"",startsAt,endsAt,"",status,priceMinor);jdbc.update("UPDATE activity_session SET starts_at=?,ends_at=?,status=?,price_minor=? WHERE id=?",java.sql.Timestamp.from(start),java.sql.Timestamp.from(end),status,priceMinor,sessionId);String activityId=sessionActivityId(sessionId);if(activityId!=null)refreshActivityStatus(activityId);return sessionById(sessionId);}
 public Session publishSession(String sessionId){if(jdbc!=null)jdbc.update("UPDATE activity_session SET status='ONSALE' WHERE id=?",sessionId);String activityId=sessionActivityId(sessionId);if(activityId!=null)refreshActivityStatus(activityId);return sessionById(sessionId);}
 public Session offlineSession(String sessionId){if(jdbc!=null)jdbc.update("UPDATE activity_session SET status='OFFLINE' WHERE id=?",sessionId);String activityId=sessionActivityId(sessionId);if(activityId!=null)refreshActivityStatus(activityId);return sessionById(sessionId);}
 public void deleteSession(String sessionId){if(jdbc==null)return;String activityId=sessionActivityId(sessionId);if(activityId==null)throw new NoSuchElementException("session not found");jdbc.update("DELETE FROM seat WHERE session_id=?",sessionId);jdbc.update("DELETE FROM activity_session WHERE id=?",sessionId);refreshActivityStatus(activityId);}
 private String sessionActivityId(String sessionId){if(jdbc==null)return null;return jdbc.query("SELECT activity_id FROM activity_session WHERE id=?",(r,n)->r.getString(1),sessionId).stream().findFirst().orElse(null);}
 private void refreshActivityStatus(String activityId){if(jdbc!=null)jdbc.update("UPDATE activity SET status = CASE WHEN EXISTS (SELECT 1 FROM activity_session WHERE activity_id=? AND status='ONSALE') THEN 'PUBLISHED' ELSE 'OFFLINE' END WHERE id=?",activityId,activityId);}
 public void deleteVenue(String venueId){if(jdbc==null)return;Integer sessions=jdbc.queryForObject("SELECT COUNT(*) FROM activity_session WHERE venue_id=?",Integer.class,venueId);if(sessions!=null&&sessions>0)throw new IllegalStateException("venue has sessions and cannot be deleted");jdbc.update("DELETE FROM venue_seat WHERE venue_id=?",venueId);jdbc.update("DELETE FROM venue WHERE id=?",venueId);}
 public void deleteActivity(String activityId){if(jdbc==null)return;Integer sessions=jdbc.queryForObject("SELECT COUNT(*) FROM activity_session WHERE activity_id=?",Integer.class,activityId);if(sessions!=null&&sessions>0)throw new IllegalStateException("activity has sessions and cannot be deleted");jdbc.update("DELETE FROM activity WHERE id=?",activityId);}
 private Session sessionById(String id){if(jdbc==null)return new Session(id,"","","","","");var rows=jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status,s.price_minor FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.id=?",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status"),r.getInt("price_minor")),id);if(rows.isEmpty())throw new NoSuchElementException("session not found");return rows.get(0);}
 public Session getSession(String sessionId){return sessionById(sessionId);}
 public Seat updateSeat(String id,String status){if(jdbc==null)return new Seat(id,"",0,status);jdbc.update("UPDATE seat SET status=? WHERE id=?",status,id);var rows=jdbc.query("SELECT id,row_label,seat_number,status FROM seat WHERE id=?",(r,n)->new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),id);if(rows.isEmpty())throw new NoSuchElementException("seat not found");return rows.get(0);}
 public Seat getSeat(String id){if(jdbc==null)return new Seat(id,"",0,"AVAILABLE");var rows=jdbc.query("SELECT id,row_label,seat_number,status FROM seat WHERE id=?",(r,n)->new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),id);if(rows.isEmpty())throw new NoSuchElementException("seat not found");return rows.get(0);}
 public String activityIdForSeat(String seatId){if(jdbc==null)return null;var rows=jdbc.query("SELECT s.activity_id FROM seat x JOIN activity_session s ON s.id=x.session_id WHERE x.id=?",(r,n)->r.getString(1),seatId);return rows.stream().findFirst().orElse(null);}
 public Page<Audit> audits(String action,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));if(jdbc==null)return new Page<>(List.of(),p,s,0);String a=action==null?"":action.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM activity_audit_log WHERE (?='' OR action=?)",Integer.class,a,a);var items=jdbc.query("SELECT id,actor_user_id,action,resource_type,resource_id,trace_id,created_at FROM activity_audit_log WHERE (?='' OR action=?) ORDER BY created_at DESC LIMIT ? OFFSET ?",(r,n)->new Audit(r.getString("id"),r.getString("actor_user_id"),r.getString("action"),r.getString("resource_type"),r.getString("resource_id"),r.getString("trace_id"),r.getTimestamp("created_at").toInstant().toString()),a,a,s,p*s);return new Page<>(items,p,s,total==null?0:total);}
 public void audit(String actor,String action,String resourceType,String resourceId,String before,String after,String trace){if(jdbc!=null)jdbc.update("INSERT INTO activity_audit_log (id,actor_user_id,action,resource_type,resource_id,before_json,after_json,trace_id) VALUES (?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),actor,action,resourceType,resourceId,before,after,trace);}
 public Activity publish(String id){Activity a=get(id); if(jdbc!=null)jdbc.update("UPDATE activity SET status='PUBLISHED' WHERE id=?",id); Activity p=new Activity(a.id(),a.title(),a.organizer(),"PUBLISHED",a.layoutFrozen());activities.put(id,p);return p;}
 public Activity offline(String id){Activity a=get(id);if(jdbc!=null)jdbc.update("UPDATE activity SET status='OFFLINE' WHERE id=?",id);Activity p=new Activity(a.id(),a.title(),a.organizer(),"OFFLINE",a.layoutFrozen());activities.put(id,p);return p;}
 public Activity freezeLayout(String id){Activity a=get(id);if(!"PUBLISHED".equals(a.status())||a.layoutFrozen())throw new IllegalStateException("published layout can only be frozen once");if(jdbc!=null)jdbc.update("UPDATE activity SET layout_frozen=TRUE WHERE id=?",id);Activity p=new Activity(a.id(),a.title(),a.organizer(),a.status(),true);activities.put(id,p);return p;}
 public record Activity(String id,String title,String organizer,String status,boolean layoutFrozen){}
 public record Session(String id,String activityId,String startsAt,String endsAt,String venue,String status,int priceMinor){public Session(String id,String activityId,String startsAt,String endsAt,String venue,String status){this(id,activityId,startsAt,endsAt,venue,status,0);}}
 public record Seat(String id,String row,int number,String status){}
 public record Venue(String id,String activityId,String name,String address,int capacity){public Venue(String id,String activityId,String name,String address){this(id,activityId,name,address,0);}}
 public record VenueSeat(String id,String venueId,String areaLabel,String rowLabel,int seatNumber,String displayName,int x,int y,String seatType,boolean enabled,String status){}
 public record SeatLayout(String id,String areaLabel,String row,int number,String displayName,int x,int y,String type,String status){}
 public record SeatSnapshot(String id,String areaLabel,String rowLabel,int seatNumber,String displayName,int x,int y,String seatType,String status){}
 public record Page<T>(List<T> items,int page,int size,long total){public long totalPages(){return total==0?0:(total+size-1)/size;}}
 public record Audit(String id,String actorUserId,String action,String resourceType,String resourceId,String traceId,String createdAt){}
}
