package com.cloudticket.activity.service;
import java.util.*; import java.util.concurrent.ConcurrentHashMap; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import com.cloudticket.activity.security.ScopeAccess;
@Service public class ActivityCatalog {
 private final Map<String,Activity> activities=new ConcurrentHashMap<>();
 private final JdbcTemplate jdbc;
 public ActivityCatalog(){this.jdbc=null; seed("星河现场 · 城市之声","星河文化","PUBLISHED"); seed("海岸线音乐节","海岸现场","PUBLISHED");}
 @org.springframework.beans.factory.annotation.Autowired public ActivityCatalog(JdbcTemplate jdbc){this.jdbc=jdbc;}
 private void seed(String title,String organizer,String status){Activity a=create(title,organizer); activities.put(a.id(),new Activity(a.id(),a.title(),a.organizer(),status,false));}
 public Activity create(String title,String organizer){if(title==null||title.isBlank())throw new IllegalArgumentException("title required"); String id=UUID.randomUUID().toString(), cleanOrganizer=organizer==null?"":organizer.trim(); if(jdbc!=null)jdbc.update("INSERT INTO activity (id,title,organizer,status) VALUES (?,?,?, 'DRAFT')",id,title.trim(),cleanOrganizer); Activity a=new Activity(id,title.trim(),cleanOrganizer,"DRAFT",false);activities.put(a.id(),a);return a;}
 public Activity update(String id,String title,String organizer){Activity current=get(id);if(current.layoutFrozen())throw new IllegalStateException("layout is frozen");if(title==null||title.isBlank())throw new IllegalArgumentException("title required");String cleanTitle=title.trim(),cleanOrganizer=organizer==null?"":organizer.trim();if(jdbc!=null)jdbc.update("UPDATE activity SET title=?,organizer=? WHERE id=?",cleanTitle,cleanOrganizer,id);Activity updated=new Activity(id,cleanTitle,cleanOrganizer,current.status(),current.layoutFrozen());activities.put(id,updated);return updated;}
 public List<Activity> publicActivities(){if(jdbc!=null)return jdbc.query("SELECT id,title,organizer,status,layout_frozen FROM activity WHERE status='PUBLISHED' ORDER BY title",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")));return activities.values().stream().filter(a->"PUBLISHED".equals(a.status())).sorted(Comparator.comparing(Activity::title)).toList();}
 public Page<Activity> adminActivities(String keyword,String status,int page,int size){int safePage=Math.max(0,page), safeSize=Math.min(100,Math.max(1,size)); if(jdbc==null){var all=activities.values().stream().filter(a->(keyword==null||keyword.isBlank()||a.title().toLowerCase().contains(keyword.toLowerCase()))&&(status==null||status.isBlank()||status.equals(a.status()))).sorted(Comparator.comparing(Activity::title)).toList();int from=Math.min(safePage*safeSize,all.size());return new Page<>(all.subList(from,Math.min(from+safeSize,all.size())),safePage,safeSize,all.size());}String kw=keyword==null?"":keyword.trim();String st=status==null?"":status.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM activity WHERE (?='' OR title LIKE CONCAT('%',?,'%')) AND (?='' OR status=?)",Integer.class,kw,kw,st,st);var items=jdbc.query("SELECT id,title,organizer,status,layout_frozen FROM activity WHERE (?='' OR title LIKE CONCAT('%',?,'%')) AND (?='' OR status=?) ORDER BY title LIMIT ? OFFSET ?",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")),kw,kw,st,st,safeSize,safePage*safeSize);return new Page<>(items,safePage,safeSize,total==null?0:total);}
 public Page<Activity> adminActivities(String keyword,String status,int page,int size,String permissions,String scopes){
   if (ScopeAccess.allows(permissions, scopes, "ACTIVITY", "*")) return adminActivities(keyword,status,page,size);
   int p=Math.max(0,page), s=Math.min(100,Math.max(1,size)); String kw=keyword==null?"":keyword.trim().toLowerCase(), st=status==null?"":status.trim();
   List<Activity> all=jdbc==null?activities.values().stream().filter(a->(kw.isBlank()||a.title().toLowerCase().contains(kw))&&(st.isBlank()||st.equals(a.status()))).toList():jdbc.query("SELECT id,title,organizer,status,layout_frozen FROM activity WHERE (?='' OR title LIKE CONCAT('%',?,'%')) AND (?='' OR status=?) ORDER BY title",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")),kw,kw,st,st);
   List<Activity> visible=all.stream().filter(a->visibleActivity(a.id(),permissions,scopes)).toList(); int from=Math.min(p*s,visible.size()); return new Page<>(visible.subList(from,Math.min(from+s,visible.size())),p,s,visible.size());
 }
 private boolean visibleActivity(String id,String permissions,String scopes){
   if(ScopeAccess.allows(permissions,scopes,"ACTIVITY",id)) return true;
   if(jdbc==null||scopes==null||scopes.isBlank()) return false;
   String normalized=scopes.replace(" ","");
   if(normalized.toUpperCase().contains("SESSION:*")||normalized.toUpperCase().contains("VENUE:*")) return true;
   Integer session=jdbc.queryForObject("SELECT COUNT(*) FROM activity_session WHERE activity_id=? AND FIND_IN_SET(CONCAT('SESSION:',id), ?) > 0",Integer.class,id,normalized);
   if(session!=null&&session>0) return true;
   Integer venue=jdbc.queryForObject("SELECT COUNT(*) FROM venue WHERE activity_id=? AND FIND_IN_SET(CONCAT('VENUE:',id), ?) > 0",Integer.class,id,normalized);
   return venue!=null&&venue>0;
 }
 public Activity get(String id){if(jdbc!=null){var rows=jdbc.query("SELECT id,title,organizer,status,layout_frozen FROM activity WHERE id=?",(r,n)->new Activity(r.getString("id"),r.getString("title"),r.getString("organizer"),r.getString("status"),r.getBoolean("layout_frozen")),id);if(!rows.isEmpty())return rows.get(0);}Activity a=activities.get(id);if(a==null)throw new NoSuchElementException("activity not found");return a;}
 public List<Session> sessions(String activityId){if(jdbc==null)return List.of(new Session("20000000-0000-0000-0000-000000000001",activityId,"2026-10-01T19:30:00","2026-10-01T22:00:00","星河剧场","ONSALE"));return jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.activity_id=? ORDER BY s.starts_at",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status")),activityId);}
 public List<Seat> seats(String sessionId){if(jdbc==null)return List.of();return jdbc.query("SELECT id,row_label,seat_number,status FROM seat WHERE session_id=? ORDER BY row_label,seat_number",(r,n)->new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),sessionId);}
 public Page<Seat> seatsForActivity(String activityId,String permissions,String scopes,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));if(jdbc==null)return new Page<>(List.of(),p,s,0);var all=jdbc.query("SELECT s.id,s.row_label,s.seat_number,s.status,s.session_id FROM seat s JOIN activity_session x ON x.id=s.session_id WHERE x.activity_id=? ORDER BY x.starts_at,s.row_label,s.seat_number",(r,n)->new Object[]{new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),r.getString("session_id")},activityId);var visible=all.stream().filter(row->ScopeAccess.allows(permissions,scopes,"SESSION",(String)row[1],activityId)).map(row->(Seat)row[0]).toList();int from=Math.min(p*s,visible.size());return new Page<>(visible.subList(from,Math.min(from+s,visible.size())),p,s,visible.size());}
 public List<Venue> venues(String activityId){if(jdbc==null)return List.of();return jdbc.query("SELECT id,activity_id,name,address FROM venue WHERE (?='' OR activity_id=?) ORDER BY name",(r,n)->new Venue(r.getString("id"),r.getString("activity_id"),r.getString("name"),r.getString("address")),activityId==null?"":activityId,activityId==null?"":activityId);}
 public List<Venue> venues(String activityId,String permissions,String scopes){
   return venues(activityId).stream().filter(v->ScopeAccess.allows(permissions,scopes,"VENUE",v.id(),v.activityId())).toList();
 }
 public Venue createVenue(String activityId,String name,String address){if(activityId==null||activityId.isBlank()||name==null||name.isBlank())throw new IllegalArgumentException("activityId and name required");String id=UUID.randomUUID().toString(),cleanActivity=activityId.trim(),cleanName=name.trim(),cleanAddress=address==null?"":address.trim();if(jdbc!=null)jdbc.update("INSERT INTO venue (id,activity_id,name,address) VALUES (?,?,?,?)",id,cleanActivity,cleanName,cleanAddress);return new Venue(id,cleanActivity,cleanName,cleanAddress);}
 public Page<Session> adminSessions(String activityId,String status,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));if(jdbc==null)return new Page<>(sessions(activityId),p,s,sessions(activityId).size());String st=status==null?"":status.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM activity_session WHERE activity_id=? AND (?='' OR status=?)",Integer.class,activityId,st,st);var items=jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.activity_id=? AND (?='' OR s.status=?) ORDER BY s.starts_at LIMIT ? OFFSET ?",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status")),activityId,st,st,s,p*s);return new Page<>(items,p,s,total==null?0:total);}
 public Page<Session> adminSessions(String activityId,String status,int page,int size,String permissions,String scopes){
   if (ScopeAccess.allows(permissions,scopes,"ACTIVITY",activityId)) return adminSessions(activityId,status,page,size);
   int p=Math.max(0,page),s=Math.min(100,Math.max(1,size)); String st=status==null?"":status.trim();
   List<Session> all=jdbc==null?sessions(activityId):jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.activity_id=? AND (?='' OR s.status=?) ORDER BY s.starts_at",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status")),activityId,st,st);
   List<Session> visible=all.stream().filter(sx->{ if(ScopeAccess.allows(permissions,scopes,"SESSION",sx.id(),sx.activityId())) return true; if(jdbc==null) return false; String venueId=jdbc.query("SELECT venue_id FROM activity_session WHERE id=?",(r,n)->r.getString(1),sx.id()).stream().findFirst().orElse(""); return ScopeAccess.allows(permissions,scopes,"VENUE",venueId,sx.activityId()); }).toList();
   int from=Math.min(p*s,visible.size()); return new Page<>(visible.subList(from,Math.min(from+s,visible.size())),p,s,visible.size());
 }
 public Session createSession(String activityId,String venueId,String startsAt,String endsAt,String status){if(jdbc==null)return new Session(UUID.randomUUID().toString(),activityId,startsAt,endsAt,"",status);String id=UUID.randomUUID().toString();jdbc.update("INSERT INTO activity_session (id,activity_id,venue_id,starts_at,ends_at,status) VALUES (?,?,?,?,?,?)",id,activityId,venueId,java.sql.Timestamp.from(java.time.Instant.parse(startsAt)),java.sql.Timestamp.from(java.time.Instant.parse(endsAt)),status);var rows=jdbc.query("SELECT s.id,s.activity_id,s.starts_at,s.ends_at,v.name,s.status FROM activity_session s JOIN venue v ON v.id=s.venue_id WHERE s.id=?",(r,n)->new Session(r.getString("id"),r.getString("activity_id"),r.getTimestamp("starts_at").toInstant().toString(),r.getTimestamp("ends_at").toInstant().toString(),r.getString("name"),r.getString("status")),id);return rows.get(0);}
 public Seat updateSeat(String id,String status){if(jdbc==null)return new Seat(id,"",0,status);jdbc.update("UPDATE seat SET status=? WHERE id=?",status,id);var rows=jdbc.query("SELECT id,row_label,seat_number,status FROM seat WHERE id=?",(r,n)->new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),id);if(rows.isEmpty())throw new NoSuchElementException("seat not found");return rows.get(0);}
 public Seat getSeat(String id){if(jdbc==null)return new Seat(id,"",0,"AVAILABLE");var rows=jdbc.query("SELECT id,row_label,seat_number,status FROM seat WHERE id=?",(r,n)->new Seat(r.getString("id"),r.getString("row_label"),r.getInt("seat_number"),r.getString("status")),id);if(rows.isEmpty())throw new NoSuchElementException("seat not found");return rows.get(0);}
 public String activityIdForSeat(String seatId){if(jdbc==null)return null;var rows=jdbc.query("SELECT s.activity_id FROM seat x JOIN activity_session s ON s.id=x.session_id WHERE x.id=?",(r,n)->r.getString(1),seatId);return rows.stream().findFirst().orElse(null);}
 public Page<Audit> audits(String action,int page,int size){int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));if(jdbc==null)return new Page<>(List.of(),p,s,0);String a=action==null?"":action.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM activity_audit_log WHERE (?='' OR action=?)",Integer.class,a,a);var items=jdbc.query("SELECT id,actor_user_id,action,resource_type,resource_id,trace_id,created_at FROM activity_audit_log WHERE (?='' OR action=?) ORDER BY created_at DESC LIMIT ? OFFSET ?",(r,n)->new Audit(r.getString("id"),r.getString("actor_user_id"),r.getString("action"),r.getString("resource_type"),r.getString("resource_id"),r.getString("trace_id"),r.getTimestamp("created_at").toInstant().toString()),a,a,s,p*s);return new Page<>(items,p,s,total==null?0:total);}
 public void audit(String actor,String action,String resourceType,String resourceId,String before,String after,String trace){if(jdbc!=null)jdbc.update("INSERT INTO activity_audit_log (id,actor_user_id,action,resource_type,resource_id,before_json,after_json,trace_id) VALUES (?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),actor,action,resourceType,resourceId,before,after,trace);}
 public Activity publish(String id){Activity a=get(id); if(jdbc!=null)jdbc.update("UPDATE activity SET status='PUBLISHED' WHERE id=?",id); Activity p=new Activity(a.id(),a.title(),a.organizer(),"PUBLISHED",a.layoutFrozen());activities.put(id,p);return p;}
 public Activity offline(String id){Activity a=get(id);if(jdbc!=null)jdbc.update("UPDATE activity SET status='OFFLINE' WHERE id=?",id);Activity p=new Activity(a.id(),a.title(),a.organizer(),"OFFLINE",a.layoutFrozen());activities.put(id,p);return p;}
 public Activity freezeLayout(String id){Activity a=get(id);if(!"PUBLISHED".equals(a.status())||a.layoutFrozen())throw new IllegalStateException("published layout can only be frozen once");if(jdbc!=null)jdbc.update("UPDATE activity SET layout_frozen=TRUE WHERE id=?",id);Activity p=new Activity(a.id(),a.title(),a.organizer(),a.status(),true);activities.put(id,p);return p;}
 public record Activity(String id,String title,String organizer,String status,boolean layoutFrozen){}
 public record Session(String id,String activityId,String startsAt,String endsAt,String venue,String status){}
 public record Seat(String id,String row,int number,String status){}
 public record Venue(String id,String activityId,String name,String address){}
 public record Page<T>(List<T> items,int page,int size,long total){public long totalPages(){return total==0?0:(total+size-1)/size;}}
 public record Audit(String id,String actorUserId,String action,String resourceType,String resourceId,String traceId,String createdAt){}
}
