package com.cloudticket.promotion.service;
import com.baomidou.mybatisplus.core.toolkit.Wrappers; import com.cloudticket.promotion.domain.DiscountStrategy; import com.cloudticket.promotion.persistence.entity.CouponEntity; import com.cloudticket.promotion.persistence.entity.CouponReservationEntity; import com.cloudticket.promotion.persistence.entity.UserCouponEntity; import com.cloudticket.promotion.persistence.mapper.CouponMapper; import com.cloudticket.promotion.persistence.mapper.CouponReservationMapper; import com.cloudticket.promotion.persistence.mapper.CouponScopeMapper; import com.cloudticket.promotion.persistence.mapper.UserCouponMapper; import java.time.Instant; import java.util.UUID; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class CouponReservationService { private final CouponMapper coupons; private final CouponScopeMapper scopes; private final UserCouponMapper users; private final CouponReservationMapper reservations; private final CouponService couponService;
 public CouponReservationService(CouponMapper c,CouponScopeMapper sm,UserCouponMapper u,CouponReservationMapper r,CouponService s){coupons=c;scopes=sm;users=u;reservations=r;couponService=s;}
 @Transactional public Quote quote(String orderId,String userId,String activityId,String sessionId,int original,String couponId){if(original<0)throw new IllegalArgumentException("original amount invalid");if(couponId==null||couponId.isBlank())return new Quote(null,0,original);CouponReservationEntity previous=reservations.selectByOrder(orderId);if(previous!=null)return new Quote(previous.getReservationId(),previous.getDiscountAmountMinor(),previous.getPayableAmountMinor());UserCouponEntity uc=users.selectOne(Wrappers.<UserCouponEntity>lambdaQuery().eq(UserCouponEntity::getId,couponId).or().eq(UserCouponEntity::getCouponId,couponId).eq(UserCouponEntity::getUserId,userId));if(uc==null||!userId.equals(uc.getUserId())||!"UNUSED".equals(uc.getStatus()))throw new IllegalArgumentException("user coupon unavailable");CouponEntity coupon=coupons.selectById(uc.getCouponId());if(coupon==null||!scopeMatches(coupon.getId(),activityId,sessionId)||!valid(uc))throw new IllegalArgumentException("coupon cannot be used");DiscountStrategy strategy=couponService.strategy(couponService.toDomain(coupon));if(!strategy.canUse(original,couponService.toDomain(coupon)))throw new IllegalArgumentException("coupon threshold not met");int discount=strategy.calculateDiscount(original,couponService.toDomain(coupon));String reservationId=UUID.randomUUID().toString();if(users.hold(uc.getId(),orderId,"HELD")==0)throw new IllegalStateException("coupon already held");CouponReservationEntity row=new CouponReservationEntity();row.setReservationId(reservationId);row.setOrderId(orderId);row.setUserCouponId(uc.getId());row.setCouponId(coupon.getId());row.setUserId(userId);row.setOriginalAmountMinor(original);row.setDiscountAmountMinor(discount);row.setPayableAmountMinor(Math.max(0,original-discount));row.setStatus("HELD");reservations.insert(row);return new Quote(reservationId,discount,row.getPayableAmountMinor());}
 @Transactional public void transition(String reservationId,String action){CouponReservationEntity r=reservations.selectById(reservationId);if(r==null)return;String from=r.getStatus();String to=switch(action.toUpperCase()){case "CONSUME"->"CONSUMED";case "RELEASE"->"RELEASED";case "RESTORE"->"RESTORED";default->throw new IllegalArgumentException("unknown reservation action");};if(from.equals(to)||!"HELD".equals(from))return;if(reservations.transition(reservationId,from,to)>0){String userStatus="CONSUME".equalsIgnoreCase(action)?"USED":"UNUSED";users.transition(r.getUserCouponId(),fromUserStatus(from),userStatus);}}
 private String fromUserStatus(String ignored){return "HELD";}
 private boolean valid(UserCouponEntity u){return u.getTermEndAt()==null||Instant.now().isBefore(u.getTermEndAt());}
 private boolean scopeMatches(String id,String activity,String session){var rows=scopes.selectByCoupon(id);return rows.isEmpty()||rows.stream().anyMatch(x->"ALL".equalsIgnoreCase(x.getResourceType())||("ACTIVITY".equalsIgnoreCase(x.getResourceType())&&java.util.Objects.equals(x.getResourceId(),activity))||("SESSION".equalsIgnoreCase(x.getResourceType())&&java.util.Objects.equals(x.getResourceId(),session)));}
 public record Quote(String reservationId,int discountAmountMinor,int payableAmountMinor){}
}
