package com.cloudticket.comment.api;
import com.cloudticket.comment.persistence.entity.CommentEntity; import com.cloudticket.comment.service.CommentLikeService; import com.cloudticket.comment.service.CommentService; import com.cloudticket.common.security.RequirePermission; import java.util.Map; import org.springframework.web.bind.annotation.*;
@RestController public class CommentController { private final CommentService service; private final CommentLikeService likes; public CommentController(CommentService s,CommentLikeService l){service=s;likes=l;}
 @GetMapping("/api/activities/{activityId}/comments") public Map<String,Object> page(@PathVariable String activityId,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return service.page(activityId,page,size).asMap();}
 @GetMapping("/api/comments/{id}/replies") public Map<String,Object> replies(@PathVariable String id){return Map.of("items",service.replies(id));}
 @GetMapping("/api/comments/likes") public Map<String,Object> liked(@RequestHeader("X-User-Id") String user,@RequestParam(defaultValue="") String ids){var commentIds=ids.isBlank()?java.util.List.<String>of():java.util.Arrays.stream(ids.split(",")).filter(s->!s.isBlank()).distinct().limit(100).toList();return Map.of("likedIds",likes.likedCommentIds(user,commentIds));}
 @PostMapping("/api/activities/{activityId}/comments") public CommentEntity create(@RequestHeader("X-User-Id") String user,@PathVariable String activityId,@RequestBody Map<String,String> body){return service.create(user,activityId,body.get("parentId"),body.get("content"));}
 @PostMapping("/api/comments/{id}/replies") public CommentEntity reply(@RequestHeader("X-User-Id") String user,@PathVariable String id,@RequestBody Map<String,String> body){return service.reply(user,id,body.get("content"));}
 @PostMapping("/api/comments/{id}/like") public Map<String,Object> like(@RequestHeader("X-User-Id") String user,@PathVariable String id){var r=likes.like(id,user);return Map.of("liked",r.liked(),"likeCount",r.likeCount());}
 @DeleteMapping("/api/comments/{id}/like") public Map<String,Object> unlike(@RequestHeader("X-User-Id") String user,@PathVariable String id){var r=likes.unlike(id,user);return Map.of("liked",r.liked(),"likeCount",r.likeCount());}
 @RequirePermission("comment:moderate") @GetMapping("/api/admin/comments") public Map<String,Object> adminPage(@RequestParam(defaultValue="") String activityId,@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="20") int size){return service.adminPage(activityId,status,page,size).asMap();}
 @RequirePermission("comment:moderate") @PutMapping("/api/admin/comments/{id}/{action}") public Map<String,Object> moderate(@PathVariable String id,@PathVariable String action){service.moderate(id,"hide".equalsIgnoreCase(action)?"HIDDEN":"VISIBLE");return Map.of("status","OK");}
}
