<script setup lang="ts">
import { onMounted, ref } from 'vue'
import VenueInventoryView from './VenueInventoryView.vue'
import { adminActivities, adminActivitySessions, adminAudits, adminInventory, adminOrders, adminRefunds, adminScopes, adminUsers, adminRoles, adminVenuePage, bindAdminScope, createAdminActivity, createAdminScope, createAdminSession, deleteAdminActivity, deleteAdminSession, grantUserRole, offlineAdminSession, publishAdminSession, reviewRefund, updateAdminActivity, updateAdminSession, updateInventorySeat, updateUserStatus, assertTimeOrder, toLocalIso, type AdminActivity, type AdminOrder, type AdminRole, type AdminScope, type AdminSession, type AdminUser, type AdminVenue, type Audit, type InventorySeat, type RefundRequest } from '../../adminApi'

const props = defineProps<{ permissions: string[] }>()
const active = ref('activities'), rows = ref<AdminActivity[]>([]), orders = ref<AdminOrder[]>([]), refunds = ref<RefundRequest[]>([]), users = ref<AdminUser[]>([]), audits = ref<Audit[]>([]), inventory = ref<InventorySeat[]>([]), scopes = ref<AdminScope[]>([]), roles = ref<AdminRole[]>([]), userRoles = ref<Record<string, string>>({})
const sessions = ref<AdminSession[]>([]), venues = ref<AdminVenue[]>([]), selectedActivityId = ref(''), sessionStatus = ref(''), sessionPage = ref(0), sessionTotal = ref(0), sessionVenueId = ref(''), startsAt = ref(''), endsAt = ref(''), sessionPrice = ref(0)
const page = ref(0), total = ref(0), keyword = ref(''), status = ref(''), error = ref(''), title = ref(''), organizer = ref(''), editingActivity = ref<AdminActivity|null>(null), showActivityModal = ref(false), showSessionModal = ref(false), editingSession = ref<AdminSession|null>(null)
const scopeType = ref('ACTIVITY'), scopeResourceId = ref(''), loading = ref(false)
const can = (permission: string) => props.permissions.includes(permission) || props.permissions.includes('system:config')
const activityStatusLabel = (value: string) => value === 'PUBLISHED' ? '上线' : value === 'OFFLINE' ? '下线' : '草稿'
const formatError = (err: unknown, fallback: string) => { if (err instanceof Error && err.message.startsWith('REQUEST_')) { const code = err.message.replace('REQUEST_', ''); return `${fallback}（HTTP ${code}）` } return fallback }
async function load() { loading.value = true; error.value = ''; try { const result = await adminActivities({ keyword: keyword.value, status: status.value, page: page.value, size: 10 }); rows.value = result.items; total.value = result.total } catch (e) { error.value = formatError(e, '活动数据加载失败，请检查权限或服务状态。') } finally { loading.value = false } }
async function loadOrders() { loading.value = true; error.value = ''; try { const result = await adminOrders({ status: status.value, page: page.value, size: 10 }); orders.value = result.items; total.value = result.total } catch (e) { error.value = formatError(e, '订单数据加载失败，请检查权限或服务状态。') } finally { loading.value = false } }
async function loadRefunds() { loading.value = true; error.value = ''; try { const result = await adminRefunds({ status: status.value, page: page.value, size: 10 }); refunds.value = result.items; total.value = result.total } catch (e) { error.value = formatError(e, '退款申请加载失败，请检查权限或服务状态。') } finally { loading.value = false } }
async function decideRefund(row: RefundRequest, decision: 'approve' | 'reject') { try { await reviewRefund(row.id, decision); await loadRefunds() } catch { error.value = '退款审核失败。' } }
async function loadUsers() { loading.value = true; error.value = ''; try { const result = await adminUsers({ keyword: keyword.value, status: status.value, page: page.value, size: 10 }); users.value = result.items; total.value = result.total } catch (e) { error.value = formatError(e, '用户数据加载失败，请检查权限或服务状态。') } finally { loading.value = false } }
async function loadRoles() { if (!can('role:manage')) return; try { roles.value = (await adminRoles()).items } catch { error.value = '角色列表加载失败，请检查权限或服务状态。' } }
async function assignRole(user: AdminUser) { const roleCode = userRoles.value[user.id]; if (!roleCode) return; try { await grantUserRole(user.id, roleCode); userRoles.value[user.id] = ''; error.value = '' } catch { error.value = '角色授予失败，请确认权限和用户状态。' } }
async function loadAudits() { loading.value = true; error.value = ''; try { const result = await adminAudits({ action: keyword.value, page: page.value, size: 10 }); audits.value = result.items; total.value = result.total } catch (e) { error.value = formatError(e, '审计数据加载失败，请检查权限或服务状态。') } finally { loading.value = false } }
async function loadScopes() { loading.value = true; error.value = ''; try { const result = await adminScopes({ resourceType: status.value, page: page.value, size: 10 }); scopes.value = result.items; total.value = result.total } catch (e) { error.value = formatError(e, 'Scope 数据加载失败，请检查权限或服务状态。') } finally { loading.value = false } }
async function loadInventory() { loading.value = true; error.value = ''; try { const result = await adminInventory({ status: status.value, page: page.value, size: 10 }); inventory.value = result.items; total.value = result.total } catch (e) { error.value = formatError(e, '库存数据加载失败，请检查权限或服务状态。') } finally { loading.value = false } }
async function loadSessions() { if (!selectedActivityId.value) return; loading.value = true; error.value = ''; try { const result = await adminActivitySessions(selectedActivityId.value, { status: sessionStatus.value, page: sessionPage.value, size: 10 }); sessions.value = result.items; sessionTotal.value = result.total } catch (e) { error.value = formatError(e, '场次数据加载失败。') } finally { loading.value = false } }
async function loadVenues() { try { venues.value = (await adminVenuePage({ size: 100 })).items } catch { venues.value = []; error.value = '场馆数据加载失败。' } }
function openCreateActivity() { editingActivity.value = null; title.value = ''; organizer.value = ''; showActivityModal.value = true }
function openEditActivity(row: AdminActivity) { editingActivity.value = row; title.value = row.title; organizer.value = row.organizer; showActivityModal.value = true }
async function saveActivity() { if (!title.value.trim()) return; try { if (editingActivity.value) await updateAdminActivity(editingActivity.value.id, title.value, organizer.value); else await createAdminActivity(title.value, organizer.value); showActivityModal.value = false; page.value = 0; await load() } catch (e) { error.value = formatError(e, '活动保存失败。') } }
async function showSessions(row: AdminActivity) { selectedActivityId.value = row.id; sessionPage.value = 0; sessionVenueId.value = ''; startsAt.value = ''; endsAt.value = ''; sessionPrice.value = 0; editingSession.value = null; showSessionModal.value = true; await loadVenues(); await loadSessions() }
function openEditSession(row: AdminSession) { editingSession.value = row; startsAt.value = toLocalInput(row.startsAt); endsAt.value = toLocalInput(row.endsAt || row.startsAt); sessionPrice.value = (row.priceMinor ?? 0) / 100 }
function toLocalInput(value: string) { const d = new Date(value); const off = d.getTimezoneOffset(); return new Date(d.getTime() - off * 60000).toISOString().slice(0, 16) }
async function saveSession() { if (!selectedActivityId.value) return; if (!assertTimeOrder(startsAt.value, endsAt.value)) { error.value = '结束时间必须晚于开始时间。'; return } try { const price = Math.round(sessionPrice.value * 100); const body = { venueId: sessionVenueId.value, startsAt: toLocalIso(startsAt.value), endsAt: toLocalIso(endsAt.value), status: editingSession.value ? editingSession.value.status : 'DRAFT', price }; if (editingSession.value) await updateAdminSession(selectedActivityId.value, editingSession.value.id, { startsAt: body.startsAt, endsAt: body.endsAt, status: editingSession.value.status, price }); else await createAdminSession(selectedActivityId.value, body); editingSession.value = null; sessionVenueId.value = ''; startsAt.value = ''; endsAt.value = ''; sessionPrice.value = 0; sessionPage.value = 0; await loadSessions() } catch (e) { error.value = formatError(e, '场次保存失败，请确认场馆和时间格式。') } }
async function publishSession(row: AdminSession) { try { await publishAdminSession(selectedActivityId.value, row.id); await loadSessions(); await load() } catch { error.value = '场次发布失败。' } }
async function offlineSession(row: AdminSession) { try { await offlineAdminSession(selectedActivityId.value, row.id); await loadSessions(); await load() } catch { error.value = '场次下线失败。' } }
async function removeActivity(row: AdminActivity) { if (!window.confirm(`确定删除活动“${row.title}”吗？`)) return; try { await deleteAdminActivity(row.id); page.value = 0; await load() } catch (e) { error.value = formatError(e, '活动删除失败，可能存在关联场次。') } }
async function removeSession(row: AdminSession) { if (!window.confirm('确定删除该场次吗？')) return; try { await deleteAdminSession(selectedActivityId.value, row.id); await loadSessions(); await load() } catch (e) { error.value = formatError(e, '场次删除失败。') } }
async function toggleSeat(row: InventorySeat) { try { await updateInventorySeat(row.id, row.status === 'AVAILABLE' ? 'LOCKED' : 'AVAILABLE', '管理员调整'); await loadInventory() } catch { error.value = '库存状态更新失败。' } }
async function toggleUser(user: AdminUser) { try { await updateUserStatus(user.id, user.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'); await loadUsers() } catch { error.value = '用户状态更新失败。' } }
async function createScope() { if (!scopeResourceId.value.trim()) return; try { await createAdminScope(scopeType.value, scopeResourceId.value.trim()); scopeResourceId.value = ''; page.value = 0; await loadScopes() } catch { error.value = 'Scope 创建失败，请确认资源 ID。' } }
async function bindScope(scope: AdminScope) { const userId = window.prompt('输入要绑定的用户 ID'); if (!userId?.trim()) return; try { await bindAdminScope(scope.id, userId.trim()); await loadScopes() } catch { error.value = 'Scope 绑定失败。' } }
onMounted(() => { load(); loadRoles() })
</script>

<template>
  <section class="admin-console">
    <div class="admin-nav">
      <strong>管理后台</strong>
      <button v-if="can('activity:read') || can('activity:write') || can('activity:publish')" data-testid="admin-module-activities" type="button" :class="{active: active === 'activities'}" @click="active='activities'; page=0; load()">活动管理</button>
      <button v-if="can('venue:read') || can('seat-layout:write')" data-testid="admin-module-venues" type="button" :class="{active: active === 'venues'}" @click="active='venues'">场馆与库存</button>
      <button v-if="can('order:read')" data-testid="admin-module-orders" type="button" :class="{active: active === 'orders'}" @click="active='orders'; page=0; loadOrders()">订单管理</button>
      <button v-if="can('order:refund')" type="button" :class="{active: active === 'refunds'}" @click="active='refunds'; page=0; loadRefunds()">退款审核</button>
      <button v-if="can('inventory:read')" type="button" :class="{active: active === 'inventory'}" @click="active='inventory'; page=0; loadInventory()">库存管理</button>
      <button v-if="can('user:manage')" type="button" :class="{active: active === 'users'}" @click="active='users'; page=0; loadUsers()">用户与角色</button>
      <button v-if="can('scope:manage')" data-testid="admin-module-scopes" type="button" :class="{active: active === 'scopes'}" @click="active='scopes'; page=0; loadScopes()">资源 Scope</button>
      <button v-if="can('audit:read')" data-testid="admin-module-audit" type="button" :class="{active: active === 'audit'}" @click="active='audit'; page=0; loadAudits()">审计日志</button>
    </div>

    <div class="admin-content">
      <div v-if="active === 'activities'">
        <div class="admin-heading"><div><p class="eyebrow">OPERATIONS</p><h2>活动管理</h2></div><div class="admin-actions"><button v-if="can('activity:write')" class="primary-btn compact" @click="openCreateActivity">创建活动</button><button class="secondary-btn" @click="load">刷新</button></div></div>
        <div class="admin-filters"><input v-model="keyword" placeholder="搜索活动" @keyup.enter="page=0;load()"><select v-model="status" @change="page=0;load()"><option value="">全部状态</option><option value="PUBLISHED">上线</option><option value="OFFLINE">下线</option></select></div>
        <p v-if="error" class="alert">{{ error }}</p>
        <p v-if="loading">正在加载...</p>
        <table v-else class="admin-table"><thead><tr><th>活动</th><th>主办方</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{ row.title }}</td><td>{{ row.organizer }}</td><td>{{ activityStatusLabel(row.status) }}</td><td><button v-if="can('activity:write')" class="icon-btn" @click="openEditActivity(row)">编辑</button><button v-if="can('session:write')" class="icon-btn" @click="showSessions(row)">场次</button><button v-if="can('activity:write') && row.status !== 'PUBLISHED'" class="icon-btn danger" @click="removeActivity(row)">删除</button></td></tr><tr v-if="!rows.length"><td colspan="4">暂无符合条件的活动</td></tr></tbody></table>
        <div class="pagination"><button class="secondary-btn" :disabled="page === 0" @click="page--;load()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page + 1) * 10 >= total" @click="page++;load()">下一页</button></div>
      </div>

      <div v-else-if="active === 'venues'"><VenueInventoryView :permissions="permissions" /></div>

      <div v-else-if="active === 'orders'"><div class="admin-heading"><h2>订单管理</h2><button class="secondary-btn" @click="loadOrders">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadOrders()"><option value="">全部状态</option><option value="PENDING">待处理</option><option value="PAID">已支付</option><option value="CANCELLED">已取消</option></select></div><p v-if="error" class="alert">{{ error }}</p><p v-if="loading">正在加载...</p><table v-else class="admin-table"><thead><tr><th>订单号</th><th>用户</th><th>场次</th><th>状态</th></tr></thead><tbody><tr v-for="row in orders" :key="row.id"><td>{{ row.id }}</td><td>{{ row.userId }}</td><td>{{ row.sessionId }}</td><td>{{ row.status }}</td></tr><tr v-if="!orders.length"><td colspan="4">暂无订单</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadOrders()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadOrders()">下一页</button></div></div>

      <div v-else-if="active === 'refunds'"><div class="admin-heading"><h2>退款审核</h2><button class="secondary-btn" @click="loadRefunds">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadRefunds()"><option value="">全部状态</option><option value="REQUESTED">待审核</option><option value="APPROVED">已同意</option><option value="REJECTED">已拒绝</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>订单</th><th>用户</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in refunds" :key="row.id"><td>{{ row.orderId }}</td><td>{{ row.userId }}</td><td>{{ row.reason }}</td><td>{{ row.status }}</td><td><button v-if="row.status === 'REQUESTED'" class="icon-btn" @click="decideRefund(row,'approve')">同意</button><button v-if="row.status === 'REQUESTED'" class="icon-btn" @click="decideRefund(row,'reject')">拒绝</button></td></tr><tr v-if="!refunds.length"><td colspan="5">暂无退款申请</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadRefunds()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadRefunds()">下一页</button></div></div>

      <div v-else-if="active === 'inventory'"><div class="admin-heading"><h2>库存管理</h2><button class="secondary-btn" @click="loadInventory">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadInventory()"><option value="">全部状态</option><option value="AVAILABLE">可售</option><option value="LOCKED">锁定</option><option value="SOLD">已售</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>座位</th><th>场次</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in inventory" :key="row.id"><td>{{ row.row }}{{ row.number }}</td><td>{{ row.sessionId }}</td><td>{{ row.status }}</td><td><button class="icon-btn" @click="toggleSeat(row)">{{ row.status === 'AVAILABLE' ? '锁定' : '设为可售' }}</button></td></tr><tr v-if="!inventory.length"><td colspan="4">暂无库存</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadInventory()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadInventory()">下一页</button></div></div>

      <div v-else-if="active === 'users'"><div class="admin-heading"><h2>用户管理</h2><button class="secondary-btn" @click="loadUsers">刷新</button></div><div class="admin-filters"><input v-model="keyword" placeholder="手机号、邮箱或昵称" @keyup.enter="page=0;loadUsers()"><select v-model="status" @change="page=0;loadUsers()"><option value="">全部状态</option><option value="ACTIVE">正常</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>用户</th><th>联系方式</th><th>状态</th><th v-if="can('role:manage')">授予角色</th><th>操作</th></tr></thead><tbody><tr v-for="row in users" :key="row.id"><td>{{ row.nickname || '未设置' }}</td><td>{{ row.phone || row.email }}</td><td>{{ row.status }}</td><td v-if="can('role:manage')"><select v-model="userRoles[row.id]" @change="assignRole(row)"><option value="">选择角色</option><option v-for="role in roles" :key="role.code" :value="role.code">{{ role.name }}（{{ role.code }}）</option></select></td><td><button class="icon-btn" @click="toggleUser(row)">{{ row.status === 'ACTIVE' ? '停用' : '启用' }}</button></td></tr><tr v-if="!users.length"><td :colspan="can('role:manage') ? 5 : 4">暂无用户</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadUsers()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadUsers()">下一页</button></div></div>

      <div v-else-if="active === 'scopes'"><div class="admin-heading"><h2>资源 Scope</h2><button class="secondary-btn" @click="loadScopes">刷新</button></div><form class="admin-form" @submit.prevent="createScope"><select v-model="scopeType"><option value="ACTIVITY">活动</option><option value="VENUE">场馆</option><option value="SESSION">场次</option><option value="AREA">区域</option></select><input v-model="scopeResourceId" placeholder="资源 UUID"><button class="primary-btn">创建 Scope</button></form><div class="admin-filters"><select v-model="status" @change="page=0;loadScopes()"><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table class="admin-table"><thead><tr><th>类型</th><th>资源 ID</th><th>状态</th><th>绑定用户</th><th>操作</th></tr></thead><tbody><tr v-for="row in scopes" :key="row.id"><td>{{ row.resourceType }}</td><td>{{ row.resourceId }}</td><td>{{ row.status }}</td><td>{{ row.userCount }}</td><td><button class="icon-btn" @click="bindScope(row)">绑定用户</button></td></tr><tr v-if="!scopes.length"><td colspan="5">暂无 Scope</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadScopes()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadScopes()">下一页</button></div></div>

      <div v-else-if="active === 'audit'"><div class="admin-heading"><h2>审计日志</h2><button class="secondary-btn" @click="loadAudits">刷新</button></div><div class="admin-filters"><input v-model="keyword" placeholder="按操作筛选" @keyup.enter="page=0;loadAudits()"></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>时间</th><th>操作</th><th>资源</th><th>操作者</th></tr></thead><tbody><tr v-for="row in audits" :key="row.id"><td>{{ row.createdAt }}</td><td>{{ row.action }}</td><td>{{ row.resourceType }}/{{ row.resourceId }}</td><td>{{ row.actor }}</td></tr><tr v-if="!audits.length"><td colspan="4">暂无审计记录</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadAudits()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadAudits()">下一页</button></div></div>
    </div>
  </section>

  <div v-if="showActivityModal" class="modal-backdrop" @click.self="showActivityModal=false"><form class="modal-card" @submit.prevent="saveActivity"><div class="admin-heading"><h3>{{ editingActivity ? '编辑活动' : '创建活动' }}</h3><button type="button" class="icon-btn" @click="showActivityModal=false">×</button></div><input v-model="title" placeholder="活动名称" required><input v-model="organizer" placeholder="主办方"><div class="modal-actions"><button type="button" class="secondary-btn" @click="showActivityModal=false">取消</button><button class="primary-btn">保存</button></div></form></div>

  <div v-if="showSessionModal" class="modal-backdrop" @click.self="showSessionModal=false"><section class="modal-card wide"><div class="admin-heading"><div><h3>场次管理</h3><small>{{ selectedActivityId }}</small></div><button class="icon-btn" @click="showSessionModal=false">×</button></div><p v-if="error" class="alert">{{ error }}</p><form v-if="can('session:write')" class="admin-form" @submit.prevent="saveSession"><select v-model="sessionVenueId" required :disabled="!!editingSession"><option value="" disabled>选择场馆</option><option v-for="venue in venues" :key="venue.id" :value="venue.id">{{ venue.name }}（{{ venue.capacity }}座）</option></select><input v-model="startsAt" type="datetime-local" required><input v-model="endsAt" type="datetime-local" :min="startsAt" required><input v-model.number="sessionPrice" type="number" min="0" step="0.01" data-testid="session-price" placeholder="票价（元）"><button class="primary-btn">{{ editingSession ? '保存场次' : '创建场次' }}</button></form><div class="admin-filters"><select v-model="sessionStatus" @change="sessionPage=0;loadSessions()"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="ONSALE">售票中</option><option value="OFFLINE">已下线</option></select></div><table class="admin-table"><thead><tr><th>场馆</th><th>开始</th><th>结束</th><th>票价</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in sessions" :key="row.id"><td>{{ row.venue }}</td><td>{{ new Date(row.startsAt).toLocaleString('zh-CN') }}</td><td>{{ row.endsAt ? new Date(row.endsAt).toLocaleString('zh-CN') : '-' }}</td><td>¥{{ ((row.priceMinor ?? 0)/100).toFixed(2) }}</td><td>{{ row.status }}</td><td><button v-if="can('session:write')" class="icon-btn" @click="openEditSession(row)">编辑</button><button v-if="can('session:write')" class="icon-btn" @click="publishSession(row)">上线</button><button v-if="can('session:write')" class="icon-btn" @click="offlineSession(row)">下线</button><button v-if="can('session:write')" class="icon-btn danger" @click="removeSession(row)">删除</button></td></tr><tr v-if="!sessions.length"><td colspan="6">暂无场次</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="sessionPage===0" @click="sessionPage--;loadSessions()">上一页</button><span>第 {{ sessionPage+1 }} 页 · 共 {{ sessionTotal }} 条</span><button class="secondary-btn" :disabled="(sessionPage+1)*10>=sessionTotal" @click="sessionPage++;loadSessions()">下一页</button></div></section></div>
</template>

<style scoped>
.floating-create{position:fixed;right:28px;bottom:28px;width:auto;padding:0 18px;z-index:5}.admin-actions{display:flex;gap:10px}.compact{width:auto;padding:0 14px}.modal-backdrop{position:fixed;inset:0;background:#050912b8;display:grid;place-items:center;z-index:20;padding:20px}.modal-card{width:min(460px,100%);max-height:90vh;overflow:auto;background:#111927;border:1px solid #31405a;border-radius:10px;padding:24px;display:grid;gap:14px;box-shadow:0 20px 70px #0008}.modal-card.wide{width:min(900px,100%)}.modal-card input,.modal-card select,.admin-form input,.admin-form select{background:#151f31;border:1px solid #31405a;color:#e8edf5;border-radius:6px;padding:11px;font:inherit}.modal-actions{display:flex;gap:10px;justify-content:flex-end}.modal-actions .primary-btn,.modal-actions .secondary-btn{width:auto;padding:0 16px;margin-top:0;height:40px}.icon-btn.danger{color:#ef8e78}
</style>
