<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminActivities, adminActivitySessions, adminAudits, adminInventory, adminOrders, adminRefunds, adminScopes, adminUsers, adminVenues, adminRoles, bindAdminScope, createAdminActivity, createAdminScope, createAdminSession, grantUserRole, offlineAdminActivity, publishAdminActivity, reviewRefund, updateInventorySeat, updateUserStatus, type AdminActivity, type AdminOrder, type AdminRole, type AdminScope, type AdminSession, type AdminUser, type AdminVenue, type Audit, type InventorySeat, type RefundRequest } from '../../adminApi'

const props = defineProps<{ permissions: string[] }>()
const active = ref('activities'), rows = ref<AdminActivity[]>([]), orders = ref<AdminOrder[]>([]), refunds = ref<RefundRequest[]>([]), users = ref<AdminUser[]>([]), audits = ref<Audit[]>([]), inventory = ref<InventorySeat[]>([]), scopes = ref<AdminScope[]>([]), roles = ref<AdminRole[]>([]), userRoles = ref<Record<string, string>>({})
const sessions = ref<AdminSession[]>([]), venues = ref<AdminVenue[]>([]), selectedActivityId = ref(''), sessionStatus = ref(''), sessionPage = ref(0), sessionTotal = ref(0), venueId = ref(''), startsAt = ref(''), endsAt = ref('')
const page = ref(0), total = ref(0), keyword = ref(''), status = ref(''), error = ref(''), title = ref(''), organizer = ref(''), scopeType = ref('ACTIVITY'), scopeResourceId = ref(''), loading = ref(false)
const can = (permission: string) => props.permissions.includes(permission) || props.permissions.includes('system:config')
async function load() { loading.value = true; error.value = ''; try { const result = await adminActivities({ keyword: keyword.value, status: status.value, page: page.value, size: 10 }); rows.value = result.items; total.value = result.total } catch { error.value = '管理数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadOrders() { loading.value = true; error.value = ''; try { const result = await adminOrders({ status: status.value, page: page.value, size: 10 }); orders.value = result.items; total.value = result.total } catch { error.value = '订单数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadRefunds() { loading.value = true; error.value = ''; try { const result = await adminRefunds({ status: status.value, page: page.value, size: 10 }); refunds.value = result.items; total.value = result.total } catch { error.value = '退款申请加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function decideRefund(row: RefundRequest, decision: 'approve' | 'reject') { try { await reviewRefund(row.id, decision); await loadRefunds() } catch { error.value = '退款审核失败。' } }
async function loadUsers() { loading.value = true; error.value = ''; try { const result = await adminUsers({ keyword: keyword.value, status: status.value, page: page.value, size: 10 }); users.value = result.items; total.value = result.total } catch { error.value = '用户数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadRoles() { if (!can('role:manage')) return; try { roles.value = (await adminRoles()).items } catch { error.value = '角色列表加载失败，请检查权限或服务状态。' } }
async function assignRole(user: AdminUser) { const roleCode = userRoles.value[user.id]; if (!roleCode) return; try { await grantUserRole(user.id, roleCode); userRoles.value[user.id] = ''; error.value = '' } catch { error.value = '角色授予失败，请确认权限和用户状态。' } }
async function loadAudits() { loading.value = true; error.value = ''; try { const result = await adminAudits({ action: keyword.value, page: page.value, size: 10 }); audits.value = result.items; total.value = result.total } catch { error.value = '审计数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadScopes() { loading.value = true; error.value = ''; try { const result = await adminScopes({ resourceType: status.value, page: page.value, size: 10 }); scopes.value = result.items; total.value = result.total } catch { error.value = 'Scope 数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadInventory() { loading.value = true; error.value = ''; try { const result = await adminInventory({ status: status.value, page: page.value, size: 10 }); inventory.value = result.items; total.value = result.total } catch { error.value = '库存数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadSessions() { if (!selectedActivityId.value) return; loading.value = true; error.value = ''; try { const result = await adminActivitySessions(selectedActivityId.value, { status: sessionStatus.value, page: sessionPage.value, size: 10 }); sessions.value = result.items; sessionTotal.value = result.total } catch { error.value = '场次数据加载失败。' } finally { loading.value = false } }
async function showSessions(row: AdminActivity) { selectedActivityId.value = row.id; sessionPage.value = 0; venueId.value = ''; try { const result = await adminVenues(row.id); venues.value = result.items } catch { venues.value = []; error.value = '场馆数据加载失败。' } await loadSessions() }
async function createSession() { if (!selectedActivityId.value || !venueId.value || !startsAt.value || !endsAt.value) return; try { await createAdminSession(selectedActivityId.value, { venueId: venueId.value, startsAt: new Date(startsAt.value).toISOString(), endsAt: new Date(endsAt.value).toISOString(), status: 'DRAFT' }); venueId.value = ''; startsAt.value = ''; endsAt.value = ''; sessionPage.value = 0; await loadSessions() } catch { error.value = '场次创建失败，请确认场馆和时间格式。' } }
async function toggleSeat(row: InventorySeat) { try { await updateInventorySeat(row.id, row.status === 'AVAILABLE' ? 'LOCKED' : 'AVAILABLE', '管理员调整'); await loadInventory() } catch { error.value = '库存状态更新失败。' } }
async function toggleUser(user: AdminUser) { try { await updateUserStatus(user.id, user.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'); await loadUsers() } catch { error.value = '用户状态更新失败。' } }
async function create() { if (!title.value.trim()) return; try { await createAdminActivity(title.value, organizer.value); title.value = ''; organizer.value = ''; page.value = 0; await load() } catch { error.value = '活动创建失败。' } }
async function createScope() { if (!scopeResourceId.value.trim()) return; try { await createAdminScope(scopeType.value, scopeResourceId.value.trim()); scopeResourceId.value = ''; page.value = 0; await loadScopes() } catch { error.value = 'Scope 创建失败，请确认资源 ID。' } }
async function bindScope(scope: AdminScope) { const userId = window.prompt('输入要绑定的用户 ID'); if (!userId?.trim()) return; try { await bindAdminScope(scope.id, userId.trim()); await loadScopes() } catch { error.value = 'Scope 绑定失败。' } }
async function publish(row: AdminActivity) { try { await publishAdminActivity(row.id); await load() } catch { error.value = '活动发布失败。' } }
async function offline(row: AdminActivity) { try { await offlineAdminActivity(row.id); await load() } catch { error.value = '活动下线失败。' } }
onMounted(() => { load(); loadRoles() })
</script>

<template>
  <section class="admin-console">
    <div class="admin-nav"><strong>管理后台</strong><button v-if="can('activity:write')" data-testid="admin-module-activities" type="button" :class="{active: active === 'activities'}" @click="active='activities'; page=0; load()">活动管理</button><button v-if="can('order:read')" data-testid="admin-module-orders" type="button" :class="{active: active === 'orders'}" @click="active='orders'; page=0; loadOrders()">订单管理</button><button v-if="can('order:refund')" type="button" :class="{active: active === 'refunds'}" @click="active='refunds'; page=0; loadRefunds()">退款审核</button><button v-if="can('inventory:read')" type="button" :class="{active: active === 'inventory'}" @click="active='inventory'; page=0; loadInventory()">库存管理</button><button v-if="can('user:manage')" type="button" :class="{active: active === 'users'}" @click="active='users'; page=0; loadUsers()">用户与角色</button><button v-if="can('scope:manage')" data-testid="admin-module-scopes" type="button" :class="{active: active === 'scopes'}" @click="active='scopes'; page=0; loadScopes()">资源 Scope</button><button v-if="can('audit:read')" data-testid="admin-module-audit" type="button" :class="{active: active === 'audit'}" @click="active='audit'; page=0; loadAudits()">审计日志</button></div>
    <div class="admin-content">
      <div v-if="active === 'activities'"><div class="admin-heading"><div><p class="eyebrow">OPERATIONS</p><h2>活动管理</h2></div><button class="secondary-btn" @click="load">刷新</button></div><form v-if="can('activity:write')" class="admin-form" @submit.prevent="create"><input v-model="title" placeholder="活动名称"><input v-model="organizer" placeholder="主办方"><button class="primary-btn">创建草稿</button></form><div class="admin-filters"><input v-model="keyword" placeholder="搜索活动" @keyup.enter="page=0;load()"><select v-model="status" @change="page=0;load()"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="PUBLISHED">已发布</option><option value="OFFLINE">已下线</option></select></div><p v-if="error" class="alert">{{ error }}</p><p v-if="loading">正在加载...</p><table v-else class="admin-table"><thead><tr><th>活动</th><th>主办方</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{ row.title }}</td><td>{{ row.organizer }}</td><td>{{ row.status }}</td><td><button v-if="row.status === 'DRAFT' && can('activity:publish')" class="icon-btn" @click="publish(row)">发布</button><button v-if="row.status === 'PUBLISHED' && can('activity:publish')" class="icon-btn" @click="offline(row)">下线</button><button v-if="can('session:write')" class="icon-btn" @click="showSessions(row)">场次</button></td></tr><tr v-if="!rows.length"><td colspan="4">暂无符合条件的活动</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page === 0" @click="page--;load()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page + 1) * 10 >= total" @click="page++;load()">下一页</button></div>
        <div v-if="selectedActivityId" class="admin-subpanel"><div class="admin-heading"><h3>场次管理</h3><button class="secondary-btn" @click="selectedActivityId='';sessions=[];venues=[]">关闭</button></div><form v-if="can('session:write')" class="admin-form" @submit.prevent="createSession"><select v-model="venueId" required><option value="" disabled>选择场馆</option><option v-for="venue in venues" :key="venue.id" :value="venue.id">{{ venue.name }} · {{ venue.address }}</option></select><input v-model="startsAt" type="datetime-local" required><input v-model="endsAt" type="datetime-local" required><button class="primary-btn" :disabled="!venues.length">创建场次</button></form><div class="admin-filters"><select v-model="sessionStatus" @change="sessionPage=0;loadSessions()"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="ONSALE">售票中</option><option value="OFFLINE">已下线</option></select></div><table class="admin-table"><thead><tr><th>场次</th><th>场馆</th><th>开始时间</th><th>状态</th></tr></thead><tbody><tr v-for="row in sessions" :key="row.id"><td>{{ row.id }}</td><td>{{ row.venue }}</td><td>{{ new Date(row.startsAt).toLocaleString('zh-CN') }}</td><td>{{ row.status }}</td></tr><tr v-if="!sessions.length"><td colspan="4">暂无场次</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="sessionPage === 0" @click="sessionPage--;loadSessions()">上一页</button><span>第 {{ sessionPage + 1 }} 页 · 共 {{ sessionTotal }} 条</span><button class="secondary-btn" :disabled="(sessionPage + 1) * 10 >= sessionTotal" @click="sessionPage++;loadSessions()">下一页</button></div></div>
      </div>
      <div v-else-if="active === 'orders'"><div class="admin-heading"><h2>订单管理</h2><button class="secondary-btn" @click="loadOrders">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadOrders()"><option value="">全部状态</option><option value="PENDING">待处理</option><option value="PAID">已支付</option><option value="CANCELLED">已取消</option></select></div><p v-if="error" class="alert">{{ error }}</p><p v-if="loading">正在加载...</p><table v-else class="admin-table"><thead><tr><th>订单号</th><th>用户</th><th>场次</th><th>状态</th></tr></thead><tbody><tr v-for="row in orders" :key="row.id"><td>{{ row.id }}</td><td>{{ row.userId }}</td><td>{{ row.sessionId }}</td><td>{{ row.status }}</td></tr><tr v-if="!orders.length"><td colspan="4">暂无订单</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadOrders()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadOrders()">下一页</button></div></div>
      <div v-else-if="active === 'refunds'"><div class="admin-heading"><h2>退款审核</h2><button class="secondary-btn" @click="loadRefunds">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadRefunds()"><option value="">全部状态</option><option value="REQUESTED">待审核</option><option value="APPROVED">已同意</option><option value="REJECTED">已拒绝</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>订单</th><th>用户</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in refunds" :key="row.id"><td>{{ row.orderId }}</td><td>{{ row.userId }}</td><td>{{ row.reason }}</td><td>{{ row.status }}</td><td><button v-if="row.status === 'REQUESTED'" class="icon-btn" @click="decideRefund(row,'approve')">同意</button><button v-if="row.status === 'REQUESTED'" class="icon-btn" @click="decideRefund(row,'reject')">拒绝</button></td></tr><tr v-if="!refunds.length"><td colspan="5">暂无退款申请</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadRefunds()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadRefunds()">下一页</button></div></div><div v-else-if="active === 'inventory'"><div class="admin-heading"><h2>库存管理</h2><button class="secondary-btn" @click="loadInventory">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadInventory()"><option value="">全部状态</option><option value="AVAILABLE">可售</option><option value="LOCKED">锁定</option><option value="SOLD">已售</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>座位</th><th>场次</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in inventory" :key="row.id"><td>{{ row.row }}{{ row.number }}</td><td>{{ row.sessionId }}</td><td>{{ row.status }}</td><td><button class="icon-btn" @click="toggleSeat(row)">{{ row.status === 'AVAILABLE' ? '锁定' : '设为可售' }}</button></td></tr><tr v-if="!inventory.length"><td colspan="4">暂无库存</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadInventory()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadInventory()">下一页</button></div></div>
      <div v-else-if="active === 'users'"><div class="admin-heading"><h2>用户管理</h2><button class="secondary-btn" @click="loadUsers">刷新</button></div><div class="admin-filters"><input v-model="keyword" placeholder="手机号、邮箱或昵称" @keyup.enter="page=0;loadUsers()"><select v-model="status" @change="page=0;loadUsers()"><option value="">全部状态</option><option value="ACTIVE">正常</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>用户</th><th>联系方式</th><th>状态</th><th v-if="can('role:manage')">授予角色</th><th>操作</th></tr></thead><tbody><tr v-for="row in users" :key="row.id"><td>{{ row.nickname || '未设置' }}</td><td>{{ row.phone || row.email }}</td><td>{{ row.status }}</td><td v-if="can('role:manage')"><select v-model="userRoles[row.id]" @change="assignRole(row)"><option value="">选择角色</option><option v-for="role in roles" :key="role.code" :value="role.code">{{ role.name }}（{{ role.code }}）</option></select></td><td><button class="icon-btn" @click="toggleUser(row)">{{ row.status === 'ACTIVE' ? '停用' : '启用' }}</button></td></tr><tr v-if="!users.length"><td :colspan="can('role:manage') ? 5 : 4">暂无用户</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadUsers()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadUsers()">下一页</button></div></div>
      <div v-else-if="active === 'scopes'"><div class="admin-heading"><h2>资源 Scope</h2><button class="secondary-btn" @click="loadScopes">刷新</button></div><form class="admin-form" @submit.prevent="createScope"><select v-model="scopeType"><option value="ACTIVITY">活动</option><option value="VENUE">场馆</option><option value="SESSION">场次</option><option value="AREA">区域</option></select><input v-model="scopeResourceId" placeholder="资源 UUID"><button class="primary-btn">创建 Scope</button></form><div class="admin-filters"><select v-model="status" @change="page=0;loadScopes()"><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table class="admin-table"><thead><tr><th>类型</th><th>资源 ID</th><th>状态</th><th>绑定用户</th><th>操作</th></tr></thead><tbody><tr v-for="row in scopes" :key="row.id"><td>{{ row.resourceType }}</td><td>{{ row.resourceId }}</td><td>{{ row.status }}</td><td>{{ row.userCount }}</td><td><button class="icon-btn" @click="bindScope(row)">绑定用户</button></td></tr><tr v-if="!scopes.length"><td colspan="5">暂无 Scope</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadScopes()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadScopes()">下一页</button></div></div>
      <div v-else-if="active === 'audit'"><div class="admin-heading"><h2>审计日志</h2><button class="secondary-btn" @click="loadAudits">刷新</button></div><div class="admin-filters"><input v-model="keyword" placeholder="按操作筛选" @keyup.enter="page=0;loadAudits()"></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>时间</th><th>操作</th><th>资源</th><th>操作者</th></tr></thead><tbody><tr v-for="row in audits" :key="row.id"><td>{{ row.createdAt }}</td><td>{{ row.action }}</td><td>{{ row.resourceType }}/{{ row.resourceId }}</td><td>{{ row.actor }}</td></tr><tr v-if="!audits.length"><td colspan="4">暂无审计记录</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadAudits()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadAudits()">下一页</button></div></div>
    </div>
  </section>
</template>
