<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminActivities, adminActivitySessions, adminAudits, adminInventory, adminOrders, adminRefunds, adminScopes, adminUsers, adminVenues, adminRoles, adminVenueSeats, bindAdminScope, createAdminActivity, createAdminScope, createAdminSession, createAdminVenue, createAdminVenueSeat, deleteAdminVenueSeat, grantUserRole, offlineAdminActivity, publishAdminActivity, reviewRefund, updateInventorySeat, updateUserStatus, type AdminActivity, type AdminOrder, type AdminRole, type AdminScope, type AdminSession, type AdminUser, type AdminVenue, type AdminVenueSeat, type Audit, type InventorySeat, type RefundRequest } from '../../adminApi'

const props = defineProps<{ permissions: string[] }>()
const active = ref('activities'), rows = ref<AdminActivity[]>([]), orders = ref<AdminOrder[]>([]), refunds = ref<RefundRequest[]>([]), users = ref<AdminUser[]>([]), audits = ref<Audit[]>([]), inventory = ref<InventorySeat[]>([]), scopes = ref<AdminScope[]>([]), roles = ref<AdminRole[]>([]), userRoles = ref<Record<string, string>>({})
const sessions = ref<AdminSession[]>([]), venues = ref<AdminVenue[]>([]), selectedActivityId = ref(''), sessionStatus = ref(''), sessionPage = ref(0), sessionTotal = ref(0), venueId = ref(''), startsAt = ref(''), endsAt = ref('')
const venueSeats = ref<AdminVenueSeat[]>([]), showActivityModal = ref(false), showConfigModal = ref(false), showVenueModal = ref(false), showSeatModal = ref(false), venueName = ref(''), venueAddress = ref(''), venueCapacity = ref(0), seatRow = ref(''), seatNumber = ref(1), seatPosition = ref('')
const page = ref(0), total = ref(0), keyword = ref(''), status = ref(''), error = ref(''), title = ref(''), organizer = ref(''), scopeType = ref('ACTIVITY'), scopeResourceId = ref(''), loading = ref(false)
const can = (permission: string) => props.permissions.includes(permission) || props.permissions.includes('system:config')
async function load() { loading.value = true; error.value = ''; try { const result = await adminActivities({ keyword: keyword.value, status: status.value, page: page.value, size: 10 }); rows.value = result.items; total.value = result.total } catch { error.value = '管理数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadOrders() { loading.value = true; error.value = ''; try { const result = await adminOrders({ status: status.value, page: page.value, size: 10 }); orders.value = result.items; total.value = result.total } catch { error.value = '订单数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadRefunds() { loading.value = true; error.value = ''; try { const result = await adminRefunds({ status: status.value, page: page.value, size: 10 }); refunds.value = result.items; total.value = result.total } catch { error.value = '退款申请加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function decideRefund(row: RefundRequest, decision: 'approve' | 'reject') { try { await reviewRefund(row.id, decision); await loadRefunds() } catch { error.value = '退款审核失败。' } }
async function loadUsers() { loading.value = true; error.value = ''; try { const result = await adminUsers({ keyword: keyword.value, status: status.value, page: page.value, size: 10 }); users.value = result.items; total.value = result.total } catch { error.value = '用户数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadRoles() { if (!can('role:manage')) return; try { roles.value = (await adminRoles()).items } catch { error.value = '角色列表加载失败，请检查权限或服务状态。' } }
async function assignRole(user: AdminUser) { const roleCode = userRoles.value[user.id]; if (!roleCode) return; try { await grantUserRole(user.id, roleCode); userRoles.value[user.id] = ''; error.value = '' } catch { error.value = '角色授予失败，请确认权限和用户状态。' } }
async function loadAudits() { loading.value = true; error.value = ''; try { const result = await adminAudits({ action: keyword.value, page: page.value, size: 10 }); audits.value = result.items; total.value = result.total } catch { error.value = '审计数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadScopes() { loading.value = true; error.value = ''; try { const result = await adminScopes({ resourceType: status.value, page: page.value, size: 10 }); scopes.value = result.items; total.value = result.total } catch { error.value = 'Scope 数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadInventory() { loading.value = true; error.value = ''; try { const result = await adminInventory({ status: status.value, page: page.value, size: 10 }); inventory.value = result.items; total.value = result.total } catch { error.value = '库存数据加载失败，请检查权限或服务状态。' } finally { loading.value = false } }
async function loadSessions() { if (!selectedActivityId.value) return; loading.value = true; error.value = ''; try { const result = await adminActivitySessions(selectedActivityId.value, { status: sessionStatus.value, page: sessionPage.value, size: 10 }); sessions.value = result.items; sessionTotal.value = result.total } catch { error.value = '场次数据加载失败。' } finally { loading.value = false } }
async function showSessions(row: AdminActivity) { selectedActivityId.value = row.id; sessionPage.value = 0; venueId.value = ''; showConfigModal.value = true; try { const result = await adminVenues(row.id); venues.value = result.items; if (venues.value.length) await loadVenueSeats(venues.value[0].id) } catch { venues.value = []; error.value = '场馆数据加载失败。' } await loadSessions() }
async function loadVenueSeats(id = venueId.value || venues.value[0]?.id) { if (!id) { venueSeats.value = []; return } try { venueSeats.value = (await adminVenueSeats(id)).items } catch { venueSeats.value = []; error.value = '座位模板加载失败。' } }
function toIso(value: string) { return new Date(value).toISOString() }
async function createSession() { if (!selectedActivityId.value || !venueId.value || !startsAt.value || !endsAt.value) return; if (new Date(startsAt.value).getTime() >= new Date(endsAt.value).getTime()) { error.value = '结束时间必须晚于开始时间。'; return } try { await createAdminSession(selectedActivityId.value, { venueId: venueId.value, startsAt: toIso(startsAt.value), endsAt: toIso(endsAt.value), status: 'DRAFT' }); venueId.value = ''; startsAt.value = ''; endsAt.value = ''; sessionPage.value = 0; await loadSessions() } catch { error.value = '场次创建失败，请确认场馆和时间格式。' } }
async function createVenue() { if (!selectedActivityId.value || !venueName.value.trim()) return; try { const created = await createAdminVenue(selectedActivityId.value, venueName.value, venueAddress.value, venueCapacity.value); venues.value = [...venues.value, created]; venueId.value = created.id; venueName.value = ''; venueAddress.value = ''; venueCapacity.value = 0; showVenueModal.value = false; await loadVenueSeats(created.id) } catch { error.value = '场馆创建失败。' } }
async function createSeat() { if (!venueId.value || !seatRow.value.trim() || seatNumber.value < 1) return; try { const created = await createAdminVenueSeat(venueId.value, { rowLabel: seatRow.value, seatNumber: seatNumber.value, position: seatPosition.value }); venueSeats.value = [...venueSeats.value, created]; seatRow.value = ''; seatNumber.value = 1; seatPosition.value = ''; showSeatModal.value = false } catch { error.value = '座位创建失败。' } }
async function removeSeat(seat: AdminVenueSeat) { try { await deleteAdminVenueSeat(seat.venueId, seat.id); venueSeats.value = venueSeats.value.filter(item => item.id !== seat.id) } catch { error.value = '座位删除失败。' } }
async function toggleSeat(row: InventorySeat) { try { await updateInventorySeat(row.id, row.status === 'AVAILABLE' ? 'LOCKED' : 'AVAILABLE', '管理员调整'); await loadInventory() } catch { error.value = '库存状态更新失败。' } }
async function toggleUser(user: AdminUser) { try { await updateUserStatus(user.id, user.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'); await loadUsers() } catch { error.value = '用户状态更新失败。' } }
async function create() { if (!title.value.trim()) return; try { const created = await createAdminActivity(title.value, organizer.value); title.value = ''; organizer.value = ''; showActivityModal.value = false; page.value = 0; await load(); showSessions(created) } catch { error.value = '活动创建失败。' } }
async function createScope() { if (!scopeResourceId.value.trim()) return; try { await createAdminScope(scopeType.value, scopeResourceId.value.trim()); scopeResourceId.value = ''; page.value = 0; await loadScopes() } catch { error.value = 'Scope 创建失败，请确认资源 ID。' } }
async function bindScope(scope: AdminScope) { const userId = window.prompt('输入要绑定的用户 ID'); if (!userId?.trim()) return; try { await bindAdminScope(scope.id, userId.trim()); await loadScopes() } catch { error.value = 'Scope 绑定失败。' } }
async function publish(row: AdminActivity) { try { await publishAdminActivity(row.id); await load() } catch { error.value = '活动发布失败。' } }
async function offline(row: AdminActivity) { try { await offlineAdminActivity(row.id); await load() } catch { error.value = '活动下线失败。' } }
onMounted(() => { load(); loadRoles() })
</script>

<template>
  <section class="admin-console">
    <div class="admin-nav"><strong>管理后台</strong><button v-if="can('activity:write')" data-testid="admin-module-activities" type="button" :class="{active: active === 'activities'}" @click="active='activities'; page=0; load()">活动管理</button><button v-if="can('order:read')" data-testid="admin-module-orders" type="button" :class="{active: active === 'orders'}" @click="active='orders'; page=0; loadOrders()">订单管理</button><button v-if="can('order:refund')" type="button" :class="{active: active === 'refunds'}" @click="active='refunds'; page=0; loadRefunds()">退款审核</button><button v-if="can('inventory:read')" type="button" :class="{active: active === 'inventory'}" @click="active='inventory'; page=0; loadInventory()">库存管理</button><button v-if="can('user:manage')" type="button" :class="{active: active === 'users'}" @click="active='users'; page=0; loadUsers()">用户与角色</button><button v-if="can('scope:manage')" data-testid="admin-module-scopes" type="button" :class="{active: active === 'scopes'}" @click="active='scopes'; page=0; loadScopes()">资源 Scope</button><button v-if="can('audit:read')" data-testid="admin-module-audit" type="button" :class="{active: active === 'audit'}" @click="active='audit'; page=0; loadAudits()">审计日志</button></div>
    <div class="admin-content">
      <div v-if="active === 'activities'"><div class="admin-heading"><div><p class="eyebrow">OPERATIONS</p><h2>活动管理</h2></div><button class="secondary-btn" @click="load">刷新</button></div><form v-if="false" class="admin-form" @submit.prevent="create"><input v-model="title" placeholder="活动名称"><input v-model="organizer" placeholder="主办方"><button class="primary-btn">创建草稿</button></form><div class="admin-filters"><input v-model="keyword" placeholder="搜索活动" @keyup.enter="page=0;load()"><select v-model="status" @change="page=0;load()"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="PUBLISHED">已发布</option><option value="OFFLINE">已下线</option></select></div><p v-if="error" class="alert">{{ error }}</p><p v-if="loading">正在加载...</p><table v-else class="admin-table"><thead><tr><th>活动</th><th>主办方</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{ row.title }}</td><td>{{ row.organizer }}</td><td>{{ row.status }}</td><td><button v-if="row.status === 'DRAFT' && can('activity:publish')" class="icon-btn" @click="publish(row)">发布</button><button v-if="row.status === 'PUBLISHED' && can('activity:publish')" class="icon-btn" @click="offline(row)">下线</button><button v-if="can('session:write')" class="icon-btn" @click="showSessions(row)">场次</button></td></tr><tr v-if="!rows.length"><td colspan="4">暂无符合条件的活动</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page === 0" @click="page--;load()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page + 1) * 10 >= total" @click="page++;load()">下一页</button></div>
        <div v-if="selectedActivityId && !showConfigModal" class="admin-subpanel"><div class="admin-heading"><h3>场次管理</h3><button class="secondary-btn" @click="selectedActivityId='';sessions=[];venues=[]">关闭</button></div><form v-if="can('session:write')" class="admin-form" @submit.prevent="createSession"><select v-model="venueId" required><option value="" disabled>选择场馆</option><option v-for="venue in venues" :key="venue.id" :value="venue.id">{{ venue.name }} · {{ venue.address }}</option></select><input v-model="startsAt" type="datetime-local" required><input v-model="endsAt" type="datetime-local" required><button class="primary-btn" :disabled="!venues.length">创建场次</button></form><div class="admin-filters"><select v-model="sessionStatus" @change="sessionPage=0;loadSessions()"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="ONSALE">售票中</option><option value="OFFLINE">已下线</option></select></div><table class="admin-table"><thead><tr><th>场次</th><th>场馆</th><th>开始时间</th><th>状态</th></tr></thead><tbody><tr v-for="row in sessions" :key="row.id"><td>{{ row.id }}</td><td>{{ row.venue }}</td><td>{{ new Date(row.startsAt).toLocaleString('zh-CN') }}</td><td>{{ row.status }}</td></tr><tr v-if="!sessions.length"><td colspan="4">暂无场次</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="sessionPage === 0" @click="sessionPage--;loadSessions()">上一页</button><span>第 {{ sessionPage + 1 }} 页 · 共 {{ sessionTotal }} 条</span><button class="secondary-btn" :disabled="(sessionPage + 1) * 10 >= sessionTotal" @click="sessionPage++;loadSessions()">下一页</button></div></div>
      </div>
      <div v-else-if="active === 'orders'"><div class="admin-heading"><h2>订单管理</h2><button class="secondary-btn" @click="loadOrders">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadOrders()"><option value="">全部状态</option><option value="PENDING">待处理</option><option value="PAID">已支付</option><option value="CANCELLED">已取消</option></select></div><p v-if="error" class="alert">{{ error }}</p><p v-if="loading">正在加载...</p><table v-else class="admin-table"><thead><tr><th>订单号</th><th>用户</th><th>场次</th><th>状态</th></tr></thead><tbody><tr v-for="row in orders" :key="row.id"><td>{{ row.id }}</td><td>{{ row.userId }}</td><td>{{ row.sessionId }}</td><td>{{ row.status }}</td></tr><tr v-if="!orders.length"><td colspan="4">暂无订单</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadOrders()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadOrders()">下一页</button></div></div>
      <div v-else-if="active === 'refunds'"><div class="admin-heading"><h2>退款审核</h2><button class="secondary-btn" @click="loadRefunds">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadRefunds()"><option value="">全部状态</option><option value="REQUESTED">待审核</option><option value="APPROVED">已同意</option><option value="REJECTED">已拒绝</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>订单</th><th>用户</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in refunds" :key="row.id"><td>{{ row.orderId }}</td><td>{{ row.userId }}</td><td>{{ row.reason }}</td><td>{{ row.status }}</td><td><button v-if="row.status === 'REQUESTED'" class="icon-btn" @click="decideRefund(row,'approve')">同意</button><button v-if="row.status === 'REQUESTED'" class="icon-btn" @click="decideRefund(row,'reject')">拒绝</button></td></tr><tr v-if="!refunds.length"><td colspan="5">暂无退款申请</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadRefunds()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadRefunds()">下一页</button></div></div><div v-else-if="active === 'inventory'"><div class="admin-heading"><h2>库存管理</h2><button class="secondary-btn" @click="loadInventory">刷新</button></div><div class="admin-filters"><select v-model="status" @change="page=0;loadInventory()"><option value="">全部状态</option><option value="AVAILABLE">可售</option><option value="LOCKED">锁定</option><option value="SOLD">已售</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>座位</th><th>场次</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in inventory" :key="row.id"><td>{{ row.row }}{{ row.number }}</td><td>{{ row.sessionId }}</td><td>{{ row.status }}</td><td><button class="icon-btn" @click="toggleSeat(row)">{{ row.status === 'AVAILABLE' ? '锁定' : '设为可售' }}</button></td></tr><tr v-if="!inventory.length"><td colspan="4">暂无库存</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadInventory()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadInventory()">下一页</button></div></div>
      <div v-else-if="active === 'users'"><div class="admin-heading"><h2>用户管理</h2><button class="secondary-btn" @click="loadUsers">刷新</button></div><div class="admin-filters"><input v-model="keyword" placeholder="手机号、邮箱或昵称" @keyup.enter="page=0;loadUsers()"><select v-model="status" @change="page=0;loadUsers()"><option value="">全部状态</option><option value="ACTIVE">正常</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>用户</th><th>联系方式</th><th>状态</th><th v-if="can('role:manage')">授予角色</th><th>操作</th></tr></thead><tbody><tr v-for="row in users" :key="row.id"><td>{{ row.nickname || '未设置' }}</td><td>{{ row.phone || row.email }}</td><td>{{ row.status }}</td><td v-if="can('role:manage')"><select v-model="userRoles[row.id]" @change="assignRole(row)"><option value="">选择角色</option><option v-for="role in roles" :key="role.code" :value="role.code">{{ role.name }}（{{ role.code }}）</option></select></td><td><button class="icon-btn" @click="toggleUser(row)">{{ row.status === 'ACTIVE' ? '停用' : '启用' }}</button></td></tr><tr v-if="!users.length"><td :colspan="can('role:manage') ? 5 : 4">暂无用户</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadUsers()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadUsers()">下一页</button></div></div>
      <div v-else-if="active === 'scopes'"><div class="admin-heading"><h2>资源 Scope</h2><button class="secondary-btn" @click="loadScopes">刷新</button></div><form class="admin-form" @submit.prevent="createScope"><select v-model="scopeType"><option value="ACTIVITY">活动</option><option value="VENUE">场馆</option><option value="SESSION">场次</option><option value="AREA">区域</option></select><input v-model="scopeResourceId" placeholder="资源 UUID"><button class="primary-btn">创建 Scope</button></form><div class="admin-filters"><select v-model="status" @change="page=0;loadScopes()"><option value="">全部状态</option><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></div><p v-if="error" class="alert">{{ error }}</p><table class="admin-table"><thead><tr><th>类型</th><th>资源 ID</th><th>状态</th><th>绑定用户</th><th>操作</th></tr></thead><tbody><tr v-for="row in scopes" :key="row.id"><td>{{ row.resourceType }}</td><td>{{ row.resourceId }}</td><td>{{ row.status }}</td><td>{{ row.userCount }}</td><td><button class="icon-btn" @click="bindScope(row)">绑定用户</button></td></tr><tr v-if="!scopes.length"><td colspan="5">暂无 Scope</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadScopes()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadScopes()">下一页</button></div></div>
      <div v-else-if="active === 'audit'"><div class="admin-heading"><h2>审计日志</h2><button class="secondary-btn" @click="loadAudits">刷新</button></div><div class="admin-filters"><input v-model="keyword" placeholder="按操作筛选" @keyup.enter="page=0;loadAudits()"></div><p v-if="error" class="alert">{{ error }}</p><table v-else class="admin-table"><thead><tr><th>时间</th><th>操作</th><th>资源</th><th>操作者</th></tr></thead><tbody><tr v-for="row in audits" :key="row.id"><td>{{ row.createdAt }}</td><td>{{ row.action }}</td><td>{{ row.resourceType }}/{{ row.resourceId }}</td><td>{{ row.actor }}</td></tr><tr v-if="!audits.length"><td colspan="4">暂无审计记录</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="page===0" @click="page--;loadAudits()">上一页</button><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><button class="secondary-btn" :disabled="(page+1)*10>=total" @click="page++;loadAudits()">下一页</button></div></div>
    </div>
  </section>
  <button v-if="active === 'activities' && can('activity:write')" class="floating-create" @click="showActivityModal=true">＋ 创建活动</button>
  <div v-if="showActivityModal" class="modal-backdrop" @click.self="showActivityModal=false"><form class="modal-card" @submit.prevent="create"><div class="admin-heading"><h3>创建活动</h3><button type="button" class="icon-btn" @click="showActivityModal=false">×</button></div><input v-model="title" placeholder="活动名称" required><input v-model="organizer" placeholder="主办方"><div class="modal-actions"><button type="button" class="secondary-btn" @click="showActivityModal=false">取消</button><button class="primary-btn">创建草稿</button></div></form></div>
  <div v-if="showConfigModal" class="modal-backdrop" @click.self="showConfigModal=false"><section class="modal-card wide"><div class="admin-heading"><div><h3>活动配置</h3><small>{{ selectedActivityId }}</small></div><button class="icon-btn" @click="showConfigModal=false">×</button></div><p v-if="error" class="alert">{{ error }}</p><div class="config-grid"><div><div class="admin-heading"><h4>场馆与座位模板</h4><button v-if="can('venue:write') || can('activity:write')" class="secondary-btn" @click="showVenueModal=true">新增场馆</button></div><select v-model="venueId" @change="loadVenueSeats()"><option value="" disabled>选择场馆</option><option v-for="venue in venues" :key="venue.id" :value="venue.id">{{ venue.name }}（{{ venue.capacity }}座）</option></select><button v-if="venueId && can('seat-layout:write')" class="secondary-btn" @click="showSeatModal=true">新增座位</button><table class="admin-table"><thead><tr><th>排</th><th>座号</th><th>位置</th><th>操作</th></tr></thead><tbody><tr v-for="seat in venueSeats" :key="seat.id"><td>{{ seat.rowLabel }}</td><td>{{ seat.seatNumber }}</td><td>{{ seat.position || '-' }}</td><td><button class="icon-btn" @click="removeSeat(seat)">删除</button></td></tr><tr v-if="!venueSeats.length"><td colspan="4">暂无座位模板</td></tr></tbody></table></div><div><div class="admin-heading"><h4>场次管理</h4></div><form v-if="can('session:write')" class="admin-form" @submit.prevent="createSession"><select v-model="venueId" required @change="loadVenueSeats()"><option value="" disabled>选择场馆</option><option v-for="venue in venues" :key="venue.id" :value="venue.id">{{ venue.name }}</option></select><input v-model="startsAt" type="datetime-local" required><input v-model="endsAt" type="datetime-local" :min="startsAt" required><button class="primary-btn" :disabled="!venues.length">创建场次</button></form><div class="admin-filters"><select v-model="sessionStatus" @change="sessionPage=0;loadSessions()"><option value="">全部状态</option><option value="DRAFT">草稿</option><option value="ONSALE">售票中</option><option value="OFFLINE">已下线</option></select></div><table class="admin-table"><thead><tr><th>场馆</th><th>开始</th><th>结束</th><th>状态</th></tr></thead><tbody><tr v-for="row in sessions" :key="row.id"><td>{{ row.venue }}</td><td>{{ new Date(row.startsAt).toLocaleString('zh-CN') }}</td><td>{{ row.endsAt ? new Date(row.endsAt).toLocaleString('zh-CN') : '-' }}</td><td>{{ row.status }}</td></tr><tr v-if="!sessions.length"><td colspan="4">暂无场次</td></tr></tbody></table><div class="pagination"><button class="secondary-btn" :disabled="sessionPage===0" @click="sessionPage--;loadSessions()">上一页</button><span>第 {{ sessionPage+1 }} 页 · 共 {{ sessionTotal }} 条</span><button class="secondary-btn" :disabled="(sessionPage+1)*10>=sessionTotal" @click="sessionPage++;loadSessions()">下一页</button></div></div></div></section></div>
  <div v-if="showVenueModal" class="modal-backdrop" @click.self="showVenueModal=false"><form class="modal-card" @submit.prevent="createVenue"><div class="admin-heading"><h3>新增场馆</h3><button type="button" class="icon-btn" @click="showVenueModal=false">×</button></div><input v-model="venueName" placeholder="场馆名称" required><input v-model="venueAddress" placeholder="地址"><input v-model.number="venueCapacity" type="number" min="0" placeholder="座位数量"><div class="modal-actions"><button type="button" class="secondary-btn" @click="showVenueModal=false">取消</button><button class="primary-btn">保存</button></div></form></div>
  <div v-if="showSeatModal" class="modal-backdrop" @click.self="showSeatModal=false"><form class="modal-card" @submit.prevent="createSeat"><div class="admin-heading"><h3>新增座位</h3><button type="button" class="icon-btn" @click="showSeatModal=false">×</button></div><input v-model="seatRow" placeholder="排号，如 A" required><input v-model.number="seatNumber" type="number" min="1" placeholder="座位号" required><input v-model="seatPosition" placeholder="位置描述"><div class="modal-actions"><button type="button" class="secondary-btn" @click="showSeatModal=false">取消</button><button class="primary-btn">保存</button></div></form></div>
</template>

<style scoped>
.floating-create{position:fixed;right:28px;bottom:28px;width:auto;padding:0 18px;z-index:5}.admin-actions{display:flex;gap:10px}.compact{width:auto;padding:0 14px}.modal-backdrop{position:fixed;inset:0;background:#050912b8;display:grid;place-items:center;z-index:20;padding:20px}.modal-card{width:min(460px,100%);max-height:90vh;overflow:auto;background:#111927;border:1px solid #31405a;border-radius:10px;padding:24px;display:grid;gap:14px;box-shadow:0 20px 70px #0008}.modal-card.wide{width:min(1000px,100%)}.modal-card input,.modal-card select,.admin-form input,.admin-form select{background:#151f31;border:1px solid #31405a;color:#e8edf5;border-radius:6px;padding:11px;font:inherit}.modal-actions{display:flex;gap:10px;justify-content:flex-end}.modal-actions .primary-btn,.modal-actions .secondary-btn{width:auto;padding:0 16px}.config-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.config-grid h4{margin:0}.config-grid .secondary-btn{width:auto;padding:0 12px;height:36px}@media(max-width:760px){.config-grid{grid-template-columns:1fr}.floating-create{right:16px;bottom:16px}}
</style>


