package com.cloudticket.comment.service;
import com.baomidou.mybatisplus.core.toolkit.Wrappers; import com.baomidou.mybatisplus.extension.plugins.pagination.Page; import com.cloudticket.comment.persistence.entity.CommentEntity; import com.cloudticket.comment.persistence.mapper.CommentMapper; import com.cloudticket.common.web.PageResult; import java.util.List; import java.util.UUID; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class CommentService { private final CommentMapper comments; public CommentService(CommentMapper c){comments=c;}
 public PageResult<CommentEntity> page(String activityId,int page,int size){int p=PageResult.safePage(page),s=PageResult.safeSize(size);Page<CommentEntity> result=comments.selectVisible(new Page<>(p+1L,s),activityId);return new PageResult<>(result.getRecords(),p,s,result.getTotal());}
 @Transactional public CommentEntity create(String userId,String activityId,String parentId,String content){if(content==null||content.isBlank()||content.length()>1000)throw new IllegalArgumentException("comment content invalid");String root=parentId;if(root!=null&&!root.isBlank()){CommentEntity parent=comments.selectById(root);if(parent==null||!activityId.equals(parent.getActivityId()))throw new IllegalArgumentException("parent comment not found");if(parent.getParentId()!=null&&!parent.getParentId().isBlank())root=parent.getParentId();}else root=null;CommentEntity row=new CommentEntity();row.setId(UUID.randomUUID().toString());row.setActivityId(activityId);row.setUserId(userId);row.setParentId(root);row.setContent(content.trim());row.setStatus("VISIBLE");row.setLikeCount(0);row.setReplyCount(0);comments.insert(row);if(root!=null)comments.incrementReply(root);return row;}
 public PageResult<CommentEntity> adminPage(String activityId,String status,int page,int size){int p=PageResult.safePage(page),s=PageResult.safeSize(size);Page<CommentEntity> result=comments.selectAdmin(new Page<>(p+1L,s),activityId==null?"":activityId,status==null?"":status);return new PageResult<>(result.getRecords(),p,s,result.getTotal());}
 public List<CommentEntity> replies(String id){return comments.selectReplies(id);} public void moderate(String id,String status){if(!"VISIBLE".equals(status)&&!"HIDDEN".equals(status))throw new IllegalArgumentException("invalid status");comments.changeStatus(id,status);}
 public CommentEntity reply(String userId,String commentId,String content){CommentEntity parent=comments.selectById(commentId);if(parent==null)throw new IllegalArgumentException("parent comment not found");return create(userId,parent.getActivityId(),commentId,content);}
}
