package com.cloudticket.auth.api;

import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;

@RestController
@RequestMapping("/api/admin/auth")
public class AuthAdminController {
  private final JdbcTemplate jdbc;
  public AuthAdminController(JdbcTemplate jdbc){this.jdbc=jdbc;}
  private void require(String permissions,String required){if(!(permissions.contains(required)||permissions.contains("system:config")))throw new SecurityException("forbidden");}
  @GetMapping("/users")
  public Map<String,Object> users(@RequestParam(name="keyword",defaultValue="") String keyword,@RequestParam(name="status",defaultValue="") String status,@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions){require(permissions,"user:read");int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));String k=keyword.trim(),st=status.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM auth_user WHERE (?='' OR phone LIKE CONCAT('%',?,'%') OR email LIKE CONCAT('%',?,'%') OR nickname LIKE CONCAT('%',?,'%')) AND (?='' OR status=?)",Integer.class,k,k,k,k,st,st);var items=jdbc.query("SELECT BIN_TO_UUID(id) id,phone,email,nickname,status,created_at FROM auth_user WHERE (?='' OR phone LIKE CONCAT('%',?,'%') OR email LIKE CONCAT('%',?,'%') OR nickname LIKE CONCAT('%',?,'%')) AND (?='' OR status=?) ORDER BY created_at DESC LIMIT ? OFFSET ?",(r,n)->Map.of("id",r.getString("id"),"phone",Objects.toString(r.getString("phone"),""),"email",Objects.toString(r.getString("email"),""),"nickname",Objects.toString(r.getString("nickname"),""),"status",r.getString("status"),"createdAt",r.getTimestamp("created_at").toInstant().toString()),k,k,k,k,st,st,s,p*s);return page(items,p,s,total==null?0:total);}
  @PutMapping("/users/{id}/status")
  public Map<String,Object> status(@PathVariable("id") String id,@RequestBody Map<String,String> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){require(permissions,"user:manage");String next=body.getOrDefault("status","ACTIVE");if(!Set.of("ACTIVE","DISABLED").contains(next))throw new IllegalArgumentException("invalid status");jdbc.update("UPDATE auth_user SET status=?,scope_version=scope_version+1 WHERE id=UUID_TO_BIN(?)",next,id);audit(actor,"USER_STATUS_CHANGED","USER",id, next,trace);return Map.of("id",id,"status",next);}
  @PutMapping("/users/{id}/role")
  public ResponseEntity<Map<String,Object>> role(@PathVariable("id") String id,@RequestBody Map<String,String> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){try { require(permissions,"role:manage"); } catch (SecurityException ex) { return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("code","FORBIDDEN","message","forbidden")); } String code=body.get("roleCode");if(code==null||code.isBlank())throw new IllegalArgumentException("roleCode required");int inserted=jdbc.update("INSERT IGNORE INTO auth_user_role(user_id,role_id) SELECT UUID_TO_BIN(?),id FROM auth_role WHERE code=?",id,code);if(inserted>0){jdbc.update("UPDATE auth_user SET scope_version=scope_version+1 WHERE id=UUID_TO_BIN(?)",id);audit(actor,"USER_ROLE_GRANTED","USER",id,code,trace);}return ResponseEntity.ok(Map.of("id",id,"roleCode",code));}
  @GetMapping("/roles") public Map<String,Object> roles(@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions){require(permissions,"role:manage");return Map.of("items",jdbc.query("SELECT BIN_TO_UUID(id) id,code,name,status FROM auth_role ORDER BY code",(r,n)->Map.of("id",r.getString("id"),"code",r.getString("code"),"name",r.getString("name"),"status",r.getString("status"))));}
  @GetMapping("/audits") public Map<String,Object> audits(@RequestParam(name="action",defaultValue="") String action,@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions){require(permissions,"audit:read");int p=Math.max(0,page),s=Math.min(100,Math.max(1,size));String a=action.trim();Integer total=jdbc.queryForObject("SELECT COUNT(*) FROM auth_audit_log WHERE (?='' OR action=?)",Integer.class,a,a);var items=jdbc.query("SELECT BIN_TO_UUID(id) id,COALESCE(BIN_TO_UUID(actor_user_id),'') actor,action,resource_type,COALESCE(BIN_TO_UUID(resource_id),'') resourceId,trace_id,created_at FROM auth_audit_log WHERE (?='' OR action=?) ORDER BY created_at DESC LIMIT ? OFFSET ?",(r,n)->Map.of("id",r.getString("id"),"actor",r.getString("actor"),"action",r.getString("action"),"resourceType",r.getString("resource_type"),"resourceId",r.getString("resourceId"),"traceId",Objects.toString(r.getString("trace_id"),""),"createdAt",r.getTimestamp("created_at").toInstant().toString()),a,a,s,p*s);return page(items,p,s,total==null?0:total);}
  private void audit(String actor,String action,String type,String resource,String after,String trace){jdbc.update("INSERT INTO auth_audit_log(id,actor_user_id,action,resource_type,resource_id,after_json,trace_id) VALUES(UUID_TO_BIN(?),UUID_TO_BIN(NULLIF(?,'')),?,?,UUID_TO_BIN(NULLIF(?,'')),JSON_QUOTE(?),?)",UUID.randomUUID().toString(),actor,action,type,resource,after,trace);}
  private Map<String,Object> page(List<?> items,int page,int size,long total){return Map.of("items",items,"page",page,"size",size,"total",total,"totalPages",total==0?0:(total+size-1)/size);}
}
