ALTER TABLE venue MODIFY activity_id CHAR(36) NULL;

ALTER TABLE venue_seat
  ADD COLUMN area_label VARCHAR(50) NOT NULL DEFAULT '',
  ADD COLUMN display_name VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN seat_type VARCHAR(20) NOT NULL DEFAULT 'REGULAR',
  ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE seat
  ADD COLUMN area_label VARCHAR(50) NOT NULL DEFAULT '',
  ADD COLUMN display_name VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN seat_type VARCHAR(20) NOT NULL DEFAULT 'REGULAR',
  ADD COLUMN position_x DECIMAL(10,2) NULL,
  ADD COLUMN position_y DECIMAL(10,2) NULL;
