CREATE DATABASE IF NOT EXISTS activity_db;
CREATE DATABASE IF NOT EXISTS inventory_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS gateway_db;
CREATE DATABASE IF NOT EXISTS cloud_ticketing_auth;
CREATE DATABASE IF NOT EXISTS promotion_db;
CREATE DATABASE IF NOT EXISTS comment_db;
