package com.cloudticket.activity.api;

import com.cloudticket.activity.service.ActivityCatalog;
import com.cloudticket.activity.client.InventorySeatProvisionClient;
import java.util.List;
import java.util.Map;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/admin/activities")
public class ActivityAdminController {
  private final ActivityCatalog catalog;
  private final InventorySeatProvisionClient inventoryClient;
  public ActivityAdminController(ActivityCatalog catalog) { this(catalog, null); }
  public ActivityAdminController(ActivityCatalog catalog, InventorySeatProvisionClient inventoryClient) { this.catalog = catalog; this.inventoryClient = inventoryClient; }
  private void allowed(String permissions) { if (!permissions.contains("activity:read") && !permissions.contains("activity:write") && !permissions.contains("activity:publish") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); }
  private void require(String permissions, String permission) { if (!permissions.contains(permission) && !permissions.contains("system:config")) throw new SecurityException("forbidden"); }
  private Map<String, Object> page(ActivityCatalog.Page<?> result) { return Map.of("items", result.items(), "page", result.page(), "size", result.size(), "total", result.total(), "totalPages", result.totalPages()); }

  @GetMapping
  public Map<String, Object> list(@RequestParam(name="keyword",defaultValue="") String keyword, @RequestParam(name="status",defaultValue="") String status, @RequestParam(name="page",defaultValue="0") int page, @RequestParam(name="size",defaultValue="20") int size, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes) { allowed(permissions); return page(catalog.adminActivities(keyword,status,page,size,permissions,scopes)); }
  @GetMapping("/{id}/sessions")
  public Map<String, Object> sessions(@PathVariable("id") String id, @RequestParam(name="status",defaultValue="") String status, @RequestParam(name="page",defaultValue="0") int page, @RequestParam(name="size",defaultValue="20") int size, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes) { allowed(permissions); return page(catalog.adminSessions(id,status,page,size,permissions,scopes)); }
  @GetMapping("/{id}/seats")
  public Map<String, Object> seats(@PathVariable("id") String id, @RequestParam(name="page",defaultValue="0") int page, @RequestParam(name="size",defaultValue="20") int size, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes) { allowed(permissions); return page(catalog.seatsForActivity(id,permissions,scopes,page,size)); }
  @GetMapping("/{id}/audits")
  public Map<String, Object> audits(@PathVariable("id") String id, @RequestParam(name="action",defaultValue="") String action, @RequestParam(name="page",defaultValue="0") int page, @RequestParam(name="size",defaultValue="20") int size, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions) { if (!permissions.contains("audit:read") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); return page(catalog.audits(action,page,size)); }
  @PostMapping
  public ActivityCatalog.Activity create(@RequestBody Map<String,String> body, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { require(permissions, "activity:write"); var a=catalog.create(body.get("title"),body.get("organizer")); catalog.audit(actor,"ACTIVITY_CREATED","ACTIVITY",a.id(),null,a.toString(),trace); return a; }
  @PutMapping("/{id}")
  public ActivityCatalog.Activity update(@PathVariable("id") String id,@RequestBody Map<String,String> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Scopes",defaultValue="") String scopes,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){if(!permissions.contains("activity:write")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",id))throw new SecurityException("forbidden");var before=catalog.get(id);var a=catalog.update(id,body.get("title"),body.get("organizer"));catalog.audit(actor,"ACTIVITY_UPDATED","ACTIVITY",id,before.toString(),a.toString(),trace);return a;}
  @PostMapping("/{id}/sessions")
  public ActivityCatalog.Session createSession(@PathVariable("id") String id, @RequestBody Map<String,String> body, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("session:write") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",id)) throw new SecurityException("forbidden"); var s=catalog.createSession(id,body.get("venueId"),body.get("startsAt"),body.get("endsAt"),body.getOrDefault("status","DRAFT")); catalog.audit(actor,"SESSION_CREATED","SESSION",s.id(),null,s.toString(),trace); if(inventoryClient!=null){var seats=catalog.sessionSeatSnapshots(s.id()).stream().map(x->Map.<String,Object>of("id",x.id(),"rowLabel",x.rowLabel(),"seatNumber",x.seatNumber(),"areaLabel",x.areaLabel(),"displayName",x.displayName(),"seatType",x.seatType(),"x",x.x(),"y",x.y(),"status",x.status())).toList(); inventoryClient.provision(s.id(),id,seats);} return s; }
  @PutMapping("/{activityId}/sessions/{sessionId}")
  public ActivityCatalog.Session updateSession(@PathVariable("activityId") String activityId, @PathVariable("sessionId") String sessionId, @RequestBody Map<String,String> body, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("session:write") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",activityId)) throw new SecurityException("forbidden"); var s=catalog.updateSession(sessionId,body.get("startsAt"),body.get("endsAt"),body.getOrDefault("status","DRAFT")); catalog.audit(actor,"SESSION_UPDATED","SESSION",sessionId,null,s.toString(),trace); return s; }
  @PostMapping("/{activityId}/sessions/{sessionId}/publish")
  public ActivityCatalog.Session publishSession(@PathVariable("activityId") String activityId, @PathVariable("sessionId") String sessionId, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("session:write") && !permissions.contains("activity:publish") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",activityId)) throw new SecurityException("forbidden"); var s=catalog.publishSession(sessionId); catalog.audit(actor,"SESSION_PUBLISHED","SESSION",sessionId,null,s.toString(),trace); return s; }
  @PostMapping("/{activityId}/sessions/{sessionId}/offline")
  public ActivityCatalog.Session offlineSession(@PathVariable("activityId") String activityId, @PathVariable("sessionId") String sessionId, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("session:write") && !permissions.contains("activity:publish") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",activityId)) throw new SecurityException("forbidden"); var s=catalog.offlineSession(sessionId); catalog.audit(actor,"SESSION_OFFLINED","SESSION",sessionId,null,s.toString(),trace); return s; }
  @PutMapping("/seats/{id}")
  public ActivityCatalog.Seat updateSeat(@PathVariable("id") String id, @RequestBody Map<String,String> body, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("seat-layout:write") && !permissions.contains("inventory:adjust") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); var activityId=catalog.activityIdForSeat(id); if(activityId==null || !com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",activityId)) throw new SecurityException("forbidden"); var before=catalog.getSeat(id); var seat=catalog.updateSeat(id,body.getOrDefault("status","AVAILABLE")); catalog.audit(actor,"SEAT_UPDATED","SEAT",seat.id(),before.toString(),seat.toString(),trace); return seat; }
  @PostMapping("/{id}/publish")
  public ActivityCatalog.Activity publish(@PathVariable("id") String id, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("activity:publish") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",id)) throw new SecurityException("forbidden"); var before=catalog.get(id); var a=catalog.publish(id); catalog.audit(actor,"ACTIVITY_PUBLISHED","ACTIVITY",id,before.toString(),a.toString(),trace); return a; }
  @PostMapping("/{id}/offline")
  public ActivityCatalog.Activity offline(@PathVariable("id") String id, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("activity:publish") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",id)) throw new SecurityException("forbidden"); var before=catalog.get(id); var a=catalog.offline(id); catalog.audit(actor,"ACTIVITY_OFFLINED","ACTIVITY",id,before.toString(),a.toString(),trace); return a; }
  @PostMapping("/{id}/layout/freeze")
  public ActivityCatalog.Activity freeze(@PathVariable("id") String id, @RequestHeader(value="X-User-Permissions",defaultValue="") String permissions, @RequestHeader(value="X-User-Scopes",defaultValue="") String scopes, @RequestHeader(value="X-User-Id",defaultValue="") String actor, @RequestHeader(value="X-Trace-Id",defaultValue="") String trace) { if (!permissions.contains("seat-layout:write") && !permissions.contains("system:config")) throw new SecurityException("forbidden"); if(!com.cloudticket.activity.security.ScopeAccess.allows(permissions,scopes,"ACTIVITY",id)) throw new SecurityException("forbidden"); var before=catalog.get(id); var a=catalog.freezeLayout(id); catalog.audit(actor,"LAYOUT_FROZEN","ACTIVITY",id,before.toString(),a.toString(),trace); return a; }
}
