package com.cloudticket.activity.api;
import com.cloudticket.activity.service.ActivityCatalog;
import java.util.Map;
import org.springframework.web.bind.annotation.*;
@RestController
@RequestMapping("/api/admin/venues")
public class VenueAdminController {
  private final ActivityCatalog catalog;
  public VenueAdminController(ActivityCatalog catalog){this.catalog=catalog;}
  @GetMapping
  public Map<String,Object> list(@RequestParam(name="keyword",defaultValue="") String keyword,@RequestParam(name="activityId",defaultValue="") String activityId,@RequestParam(name="page",defaultValue="0") int page,@RequestParam(name="size",defaultValue="20") int size,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Scopes",defaultValue="") String scopes){if(!permissions.contains("venue:read")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");if(activityId!=null&&!activityId.isBlank())return Map.of("items",catalog.venues(activityId,permissions,scopes));var p=catalog.venuesPage(keyword,page,size);return Map.of("items",p.items(),"page",p.page(),"size",p.size(),"total",p.total(),"totalPages",p.totalPages());}
  @PostMapping
  public Map<String,Object> createHttp(@RequestBody Map<String,String> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){return create(body,permissions,actor,trace);}
  public Map<String,Object> create(Map<String,String> body,String permissions,String actor,String trace){if(!permissions.contains("activity:write")&&!permissions.contains("venue:write")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");var venue=catalog.createVenue(body.get("activityId"),body.get("name"),body.get("address"));catalog.audit(actor,"VENUE_CREATED","VENUE",venue.id(),null,venue.toString(),trace);return Map.of("code","OK","message","created","traceId",trace==null?"":trace,"data",venue);}
  @PutMapping("/{venueId}")
  public Map<String,Object> update(@PathVariable String venueId,@RequestBody Map<String,String> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){if(!permissions.contains("venue:write")&&!permissions.contains("activity:write")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");var before=catalog.getVenue(venueId);var venue=catalog.updateVenue(venueId,body.get("name"),body.get("address"));catalog.audit(actor,"VENUE_UPDATED","VENUE",venueId,before.toString(),venue.toString(),trace);return Map.of("code","OK","data",venue);}
  @GetMapping("/{venueId}/seats")
  public Map<String,Object> seats(@PathVariable String venueId,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions){if(!permissions.contains("seat-layout:write")&&!permissions.contains("venue:read")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");return Map.of("items",catalog.venueSeats(venueId));}
  @PostMapping("/{venueId}/seats")
  public Map<String,Object> createSeat(@PathVariable String venueId,@RequestBody Map<String,String> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){if(!permissions.contains("seat-layout:write")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");var seat=catalog.createVenueSeat(venueId,body.get("areaLabel"),body.get("rowLabel"),parseInt(body.get("seatNumber")),body.get("displayName"),parseInt(body.get("x")),parseInt(body.get("y")),body.get("seatType"),parseBool(body.get("enabled")));catalog.audit(actor,"VENUE_SEAT_CREATED","VENUE_SEAT",seat.id(),null,seat.toString(),trace);return Map.of("code","OK","data",seat);}
  @PostMapping("/{venueId}/layout")
  public Map<String,Object> layout(@PathVariable String venueId,@RequestBody Map<String,Object> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){if(!permissions.contains("seat-layout:write")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");var seats=catalog.generateVenueLayout(venueId,String.valueOf(body.getOrDefault("mode","GRID")),body);catalog.audit(actor,"VENUE_LAYOUT_GENERATED","VENUE",venueId,null,seats.size()+" seats",trace);return Map.of("code","OK","data",seats);}
  @PutMapping("/{venueId}/seats/{seatId}")
  public Map<String,Object> updateSeat(@PathVariable String venueId,@PathVariable String seatId,@RequestBody Map<String,String> body,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){if(!permissions.contains("seat-layout:write")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");var seat=catalog.updateVenueSeat(seatId,body.get("areaLabel"),body.get("rowLabel"),parseInt(body.get("seatNumber")),body.get("displayName"),parseInt(body.get("x")),parseInt(body.get("y")),body.get("seatType"),parseBool(body.get("enabled")),body.get("status"));catalog.audit(actor,"VENUE_SEAT_UPDATED","VENUE_SEAT",seat.id(),null,seat.toString(),trace);return Map.of("code","OK","data",seat);}
  @DeleteMapping("/{venueId}/seats/{seatId}")
  public Map<String,Object> deleteSeat(@PathVariable String venueId,@PathVariable String seatId,@RequestHeader(value="X-User-Permissions",defaultValue="") String permissions,@RequestHeader(value="X-User-Id",defaultValue="") String actor,@RequestHeader(value="X-Trace-Id",defaultValue="") String trace){if(!permissions.contains("seat-layout:write")&&!permissions.contains("system:config"))throw new SecurityException("forbidden");catalog.deleteVenueSeat(seatId);catalog.audit(actor,"VENUE_SEAT_DELETED","VENUE_SEAT",seatId,null,null,trace);return Map.of("code","OK");}
  private int parseInt(String value){try{return value==null||value.isBlank()?0:Integer.parseInt(value);}catch(NumberFormatException e){throw new IllegalArgumentException("invalid number");}}
  private boolean parseBool(String value){return value==null||value.isBlank()||"true".equalsIgnoreCase(value);}
}
